"""Static contracts for the byte-frozen legacy transport and response base."""

from typing import Any, ClassVar, Generic, TypeVar

import pandas as pd
from pydantic import BaseModel

T = TypeVar("T", bound=BaseModel)

def configure(
    *,
    username: str | None = None,
    password: str | None = None,
    subscription_key: str | None = None,
) -> None: ...
def _get(
    path: str, schema: dict[str, str] | None = None, **params: Any
) -> dict[str, Any]: ...
async def _aget(
    path: str, schema: dict[str, str] | None = None, **params: Any
) -> dict[str, Any]: ...

class ErcotResponse(BaseModel, Generic[T]):
    meta: dict[str, Any] = ...
    report: dict[str, Any] = ...
    fields: list[dict[str, Any]] = ...
    data: list[T] = ...
    links: list[dict[str, Any]] | dict[str, Any] = ...
    _schema: ClassVar[dict[str, str]] = ...
    def to_df(self) -> pd.DataFrame: ...
