# Generated by tools/generate_client.py; do not edit.
from __future__ import annotations
from collections.abc import AsyncIterator, Iterator
from datetime import date, datetime, time
from decimal import Decimal
from typing import ClassVar
from ._client import Transport, Page, Row
from ._history import Archive, EiaHour
from ._xlsx import WorkbookArchive
from ._pdf import PdfArchive, PdfChartArchive

__all__ = ['ESRClient', 'rptesr_m']
class rptesr_m:
    def __init__(self, client: Transport) -> None:
        self._client = client

    class _4SecEsrChargingMwRow(Row):
        AGCExecTime: datetime | None
        DSTFlag: bool | None
        AGCExecTimeUTC: datetime | None
        systemDemand: Decimal | None
        ESRChargingMW: Decimal | None

    @property
    def _4_sec_esr_charging_mw_history(self) -> Archive[rptesr_m._4SecEsrChargingMwRow]:
        """Historical report rows, including files predating the API."""
        return Archive(self._client, 'rptesr-m', rptesr_m._4SecEsrChargingMwRow, {'AGC_EXEC_TIME': 'AGCExecTime', 'AGC_EXEC_TIME_DST': 'DSTFlag', 'AGC_EXEC_TIME_UTC': 'AGCExecTimeUTC', 'SYSTEM_DEMAND': 'systemDemand', 'ESR_CHARGING_MW': 'ESRChargingMW'}, {}, member='*.csv', datetimes={'AGCExecTime': '%m/%d/%Y %H:%M:%S', 'AGCExecTimeUTC': '%m/%d/%Y %H:%M:%S'}, variants=())

    def _4_sec_esr_charging_mw(self, *, AGCExecTimeFrom: datetime | None = None, AGCExecTimeTo: datetime | None = None, DSTFlag: bool | None = None, AGCExecTimeUTCFrom: datetime | None = None, AGCExecTimeUTCTo: datetime | None = None, systemDemandFrom: Decimal | None = None, systemDemandTo: Decimal | None = None, ESRChargingMWFrom: Decimal | None = None, ESRChargingMWTo: Decimal | None = None, page: int | None = None, size: int | None = None, sort: str | None = None, dir: str | None = None) -> Page[rptesr_m._4SecEsrChargingMwRow]:
        'Energy Storage Resource Four Second Data'
        return self._client._page('/rptesr-m/4_sec_esr_charging_mw', rptesr_m._4SecEsrChargingMwRow, {'AGCExecTimeFrom': AGCExecTimeFrom, 'AGCExecTimeTo': AGCExecTimeTo, 'DSTFlag': DSTFlag, 'AGCExecTimeUTCFrom': AGCExecTimeUTCFrom, 'AGCExecTimeUTCTo': AGCExecTimeUTCTo, 'systemDemandFrom': systemDemandFrom, 'systemDemandTo': systemDemandTo, 'ESRChargingMWFrom': ESRChargingMWFrom, 'ESRChargingMWTo': ESRChargingMWTo, 'page': page, 'size': size, 'sort': sort, 'dir': dir})

    def _4_sec_esr_charging_mw_iter(self, *, AGCExecTimeFrom: datetime | None = None, AGCExecTimeTo: datetime | None = None, DSTFlag: bool | None = None, AGCExecTimeUTCFrom: datetime | None = None, AGCExecTimeUTCTo: datetime | None = None, systemDemandFrom: Decimal | None = None, systemDemandTo: Decimal | None = None, ESRChargingMWFrom: Decimal | None = None, ESRChargingMWTo: Decimal | None = None, size: int | None = None, sort: str | None = None, dir: str | None = None) -> Iterator[rptesr_m._4SecEsrChargingMwRow]:
        'Energy Storage Resource Four Second Data'
        return self._client._iter('/rptesr-m/4_sec_esr_charging_mw', rptesr_m._4SecEsrChargingMwRow, {'AGCExecTimeFrom': AGCExecTimeFrom, 'AGCExecTimeTo': AGCExecTimeTo, 'DSTFlag': DSTFlag, 'AGCExecTimeUTCFrom': AGCExecTimeUTCFrom, 'AGCExecTimeUTCTo': AGCExecTimeUTCTo, 'systemDemandFrom': systemDemandFrom, 'systemDemandTo': systemDemandTo, 'ESRChargingMWFrom': ESRChargingMWFrom, 'ESRChargingMWTo': ESRChargingMWTo, 'size': size, 'sort': sort, 'dir': dir})

    async def _4_sec_esr_charging_mw_async(self, *, AGCExecTimeFrom: datetime | None = None, AGCExecTimeTo: datetime | None = None, DSTFlag: bool | None = None, AGCExecTimeUTCFrom: datetime | None = None, AGCExecTimeUTCTo: datetime | None = None, systemDemandFrom: Decimal | None = None, systemDemandTo: Decimal | None = None, ESRChargingMWFrom: Decimal | None = None, ESRChargingMWTo: Decimal | None = None, page: int | None = None, size: int | None = None, sort: str | None = None, dir: str | None = None) -> Page[rptesr_m._4SecEsrChargingMwRow]:
        'Energy Storage Resource Four Second Data'
        return await self._client._apage('/rptesr-m/4_sec_esr_charging_mw', rptesr_m._4SecEsrChargingMwRow, {'AGCExecTimeFrom': AGCExecTimeFrom, 'AGCExecTimeTo': AGCExecTimeTo, 'DSTFlag': DSTFlag, 'AGCExecTimeUTCFrom': AGCExecTimeUTCFrom, 'AGCExecTimeUTCTo': AGCExecTimeUTCTo, 'systemDemandFrom': systemDemandFrom, 'systemDemandTo': systemDemandTo, 'ESRChargingMWFrom': ESRChargingMWFrom, 'ESRChargingMWTo': ESRChargingMWTo, 'page': page, 'size': size, 'sort': sort, 'dir': dir})

    def _4_sec_esr_charging_mw_iter_async(self, *, AGCExecTimeFrom: datetime | None = None, AGCExecTimeTo: datetime | None = None, DSTFlag: bool | None = None, AGCExecTimeUTCFrom: datetime | None = None, AGCExecTimeUTCTo: datetime | None = None, systemDemandFrom: Decimal | None = None, systemDemandTo: Decimal | None = None, ESRChargingMWFrom: Decimal | None = None, ESRChargingMWTo: Decimal | None = None, size: int | None = None, sort: str | None = None, dir: str | None = None) -> AsyncIterator[rptesr_m._4SecEsrChargingMwRow]:
        'Energy Storage Resource Four Second Data'
        return self._client._aiter('/rptesr-m/4_sec_esr_charging_mw', rptesr_m._4SecEsrChargingMwRow, {'AGCExecTimeFrom': AGCExecTimeFrom, 'AGCExecTimeTo': AGCExecTimeTo, 'DSTFlag': DSTFlag, 'AGCExecTimeUTCFrom': AGCExecTimeUTCFrom, 'AGCExecTimeUTCTo': AGCExecTimeUTCTo, 'systemDemandFrom': systemDemandFrom, 'systemDemandTo': systemDemandTo, 'ESRChargingMWFrom': ESRChargingMWFrom, 'ESRChargingMWTo': ESRChargingMWTo, 'size': size, 'sort': sort, 'dir': dir})

class ESRClient(Transport):
    """ERCOT public data, with generated typed product methods."""
    _base_url = "https://api.ercot.com/api/public-data"
    _subscription_key_env = "ERCOT_ESR_SUBSCRIPTION_KEY"

    @property
    def rptesr_m(self) -> rptesr_m:
        return rptesr_m(self)
