# Generated by tools/generate_public.py from pinned public field metadata.
"""Observed public rows; undeclared fields and nullability fail decoding."""

from datetime import date, datetime
from decimal import Decimal

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr


class DamPrice(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        settlementPoint: Source hub, zone, or resource-node identifier.
        settlementPointPrice: Decimal source price in dollars per MWh.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictStr
    settlementPoint: StrictStr
    settlementPointPrice: Decimal
    DSTFlag: StrictBool


DAM_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "settlementPoint": "VARCHAR",
    "settlementPointPrice": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}


class DamCapacityPrice(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        ancillaryType: Source ancillary-service identifier.
        MCPC: Decimal source capacity clearing price.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictStr
    ancillaryType: StrictStr
    MCPC: Decimal
    DSTFlag: StrictBool


CAPACITY_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "ancillaryType": "VARCHAR",
    "MCPC": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}


class RealTimePrice(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        deliveryHour: Source deliveryHour value.
        deliveryInterval: Source deliveryInterval value.
        settlementPoint: Source hub, zone, or resource-node identifier.
        settlementPointType: Source settlementPointType value.
        settlementPointPrice: Decimal source price in dollars per MWh.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    deliveryHour: StrictInt
    deliveryInterval: StrictInt
    settlementPoint: StrictStr
    settlementPointType: StrictStr
    settlementPointPrice: Decimal
    DSTFlag: StrictBool


RT_FIELDS = {
    "deliveryDate": "DATE",
    "deliveryHour": "INTEGER",
    "deliveryInterval": "INTEGER",
    "settlementPoint": "VARCHAR",
    "settlementPointType": "VARCHAR",
    "settlementPointPrice": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}


class SystemLoad(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        operatingDay: Source operatingDay value.
        hourEnding: Source hour-ending label, including 24:00.
        coast: Source coast value.
        east: Source east value.
        farWest: Source farWest value.
        north: Source north value.
        northC: Source northC value.
        southern: Source southern value.
        southC: Source southC value.
        west: Source west value.
        total: Source total value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    operatingDay: date
    hourEnding: StrictStr
    coast: Decimal
    east: Decimal
    farWest: Decimal
    north: Decimal
    northC: Decimal
    southern: Decimal
    southC: Decimal
    west: Decimal
    total: Decimal
    DSTFlag: StrictBool


LOAD_FIELDS = {
    "operatingDay": "DATE",
    "hourEnding": "VARCHAR",
    "coast": "DOUBLE",
    "east": "DOUBLE",
    "farWest": "DOUBLE",
    "north": "DOUBLE",
    "northC": "DOUBLE",
    "southern": "DOUBLE",
    "southC": "DOUBLE",
    "west": "DOUBLE",
    "total": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}


class Gen55CdHrlyRtLoadFcastActual(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        currentDayFcast: Source currentDayFcast value.
        dayAheadFcast: Source dayAheadFcast value.
        actualLoad: Source actualLoad value.
        dayAheadHSL: Source dayAheadHSL value.
        currentDayHSL: Source currentDayHSL value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictInt
    currentDayFcast: Decimal
    dayAheadFcast: Decimal
    actualLoad: Decimal | None
    dayAheadHSL: Decimal
    currentDayHSL: Decimal | None
    DSTFlag: StrictBool


GEN_55_CD_HRLY_RT_LOAD_FCAST_ACTUAL_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "INTEGER",
    "currentDayFcast": "DOUBLE",
    "dayAheadFcast": "DOUBLE",
    "actualLoad": "DOUBLE",
    "dayAheadHSL": "DOUBLE",
    "currentDayHSL": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}


class Np1302AsObligation(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        qseName: Source qseName value.
        REGUPOblAdvisory: Source REGUPOblAdvisory value.
        REGDNOblAdvisory: Source REGDNOblAdvisory value.
        RRSOblAdvisory: Source RRSOblAdvisory value.
        NSPINOblAdvisory: Source NSPINOblAdvisory value.
        ECRSOblAdvisory: Source ECRSOblAdvisory value.
        REGUPOblFinal: Source REGUPOblFinal value.
        REGDNOblFinal: Source REGDNOblFinal value.
        RRSOblFinal: Source RRSOblFinal value.
        NSPINOblFinal: Source NSPINOblFinal value.
        ECRSOblFinal: Source ECRSOblFinal value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictStr
    qseName: StrictStr
    REGUPOblAdvisory: Decimal
    REGDNOblAdvisory: Decimal
    RRSOblAdvisory: Decimal
    NSPINOblAdvisory: Decimal
    ECRSOblAdvisory: Decimal
    REGUPOblFinal: Decimal
    REGDNOblFinal: Decimal
    RRSOblFinal: Decimal
    NSPINOblFinal: Decimal
    ECRSOblFinal: Decimal


NP1_302_AS_OBLIGATION_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "qseName": "VARCHAR",
    "REGUPOblAdvisory": "DOUBLE",
    "REGDNOblAdvisory": "DOUBLE",
    "RRSOblAdvisory": "DOUBLE",
    "NSPINOblAdvisory": "DOUBLE",
    "ECRSOblAdvisory": "DOUBLE",
    "REGUPOblFinal": "DOUBLE",
    "REGDNOblFinal": "DOUBLE",
    "RRSOblFinal": "DOUBLE",
    "NSPINOblFinal": "DOUBLE",
    "ECRSOblFinal": "DOUBLE",
}


class Np3161Cd7dPlusAvailResPocMargin(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        postedDatetime: Source postedDatetime value.
        operatingDate: Source operatingDate value.
        nonIRRNonPUN: Source nonIRRNonPUN value.
        ESR: Source ESR value.
        aggApprvdNonIRRNonPUN: Source aggApprvdNonIRRNonPUN value.
        aggRcvdNonIRRNonPUN: Source aggRcvdNonIRRNonPUN value.
        IRR: Source IRR value.
        aggApprvdIRR: Source aggApprvdIRR value.
        aggRcvdIRR: Source aggRcvdIRR value.
        aggApprvdESR: Source aggApprvdESR value.
        aggRcvdESR: Source aggRcvdESR value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    postedDatetime: datetime
    operatingDate: date
    nonIRRNonPUN: Decimal
    ESR: Decimal
    aggApprvdNonIRRNonPUN: Decimal
    aggRcvdNonIRRNonPUN: Decimal
    IRR: Decimal
    aggApprvdIRR: Decimal
    aggRcvdIRR: Decimal
    aggApprvdESR: Decimal
    aggRcvdESR: Decimal


NP3_161_CD_7D_PLUS_AVAIL_RES_POC_MARGIN_FIELDS = {
    "postedDatetime": "DATETIME",
    "operatingDate": "DATE",
    "nonIRRNonPUN": "DOUBLE",
    "ESR": "DOUBLE",
    "aggApprvdNonIRRNonPUN": "DOUBLE",
    "aggRcvdNonIRRNonPUN": "DOUBLE",
    "IRR": "DOUBLE",
    "aggApprvdIRR": "DOUBLE",
    "aggRcvdIRR": "DOUBLE",
    "aggApprvdESR": "DOUBLE",
    "aggRcvdESR": "DOUBLE",
}


class Np3162Cd7dAvailResPocMargin(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        postedDatetime: Source postedDatetime value.
        operatingDate: Source operatingDate value.
        hourEnding: Source hour-ending label, including 24:00.
        nonIrrNonPun: Source nonIrrNonPun value.
        aggApprvdNonIRRNonPUN: Source aggApprvdNonIRRNonPUN value.
        aggRcvdNonIRRNonPUN: Source aggRcvdNonIRRNonPUN value.
        IRR: Source IRR value.
        aggApprvdIRR: Source aggApprvdIRR value.
        aggRcvdIRR: Source aggRcvdIRR value.
        ESR: Source ESR value.
        aggApprvdESR: Source aggApprvdESR value.
        aggRcvdESR: Source aggRcvdESR value.
        repeatedHourFlag: Source repeatedHourFlag value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    postedDatetime: datetime
    operatingDate: date
    hourEnding: StrictInt
    nonIrrNonPun: Decimal
    aggApprvdNonIRRNonPUN: Decimal
    aggRcvdNonIRRNonPUN: Decimal
    IRR: Decimal
    aggApprvdIRR: Decimal
    aggRcvdIRR: Decimal
    ESR: Decimal
    aggApprvdESR: Decimal
    aggRcvdESR: Decimal
    repeatedHourFlag: StrictBool


NP3_162_CD_7D_AVAIL_RES_POC_MARGIN_FIELDS = {
    "postedDatetime": "DATETIME",
    "operatingDate": "DATE",
    "hourEnding": "INTEGER",
    "nonIrrNonPun": "DOUBLE",
    "aggApprvdNonIRRNonPUN": "DOUBLE",
    "aggRcvdNonIRRNonPUN": "DOUBLE",
    "IRR": "DOUBLE",
    "aggApprvdIRR": "DOUBLE",
    "aggRcvdIRR": "DOUBLE",
    "ESR": "DOUBLE",
    "aggApprvdESR": "DOUBLE",
    "aggRcvdESR": "DOUBLE",
    "repeatedHourFlag": "BOOLEAN",
}


class Np3233CdHourlyResOutageCap(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        postedDatetime: Source postedDatetime value.
        operatingDate: Source operatingDate value.
        hourEnding: Source hour-ending label, including 24:00.
        totalResourceMWZoneSouth: Source totalResourceMWZoneSouth value.
        totalResourceMWZoneNorth: Source totalResourceMWZoneNorth value.
        totalResourceMWZoneWest: Source totalResourceMWZoneWest value.
        totalResourceMWZoneHouston: Source totalResourceMWZoneHouston value.
        totalIRRMWZoneSouth: Source totalIRRMWZoneSouth value.
        totalIRRMWZoneNorth: Source totalIRRMWZoneNorth value.
        totalIRRMWZoneWest: Source totalIRRMWZoneWest value.
        totalIRRMWZoneHouston: Source totalIRRMWZoneHouston value.
        totalNewEquipResourceMWZoneSouth: Source totalNewEquipResourceMWZoneSouth value.
        totalNewEquipResourceMWZoneNorth: Source totalNewEquipResourceMWZoneNorth value.
        totalNewEquipResourceMWZoneWest: Source totalNewEquipResourceMWZoneWest value.
        totalNewEquipResourceMWZoneHouston: Source totalNewEquipResourceMWZoneHouston value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    postedDatetime: datetime
    operatingDate: date
    hourEnding: StrictInt
    totalResourceMWZoneSouth: StrictInt
    totalResourceMWZoneNorth: StrictInt
    totalResourceMWZoneWest: StrictInt
    totalResourceMWZoneHouston: StrictInt
    totalIRRMWZoneSouth: StrictInt
    totalIRRMWZoneNorth: StrictInt
    totalIRRMWZoneWest: StrictInt
    totalIRRMWZoneHouston: StrictInt
    totalNewEquipResourceMWZoneSouth: StrictInt
    totalNewEquipResourceMWZoneNorth: StrictInt
    totalNewEquipResourceMWZoneWest: StrictInt
    totalNewEquipResourceMWZoneHouston: StrictInt


NP3_233_CD_HOURLY_RES_OUTAGE_CAP_FIELDS = {
    "postedDatetime": "DATETIME",
    "operatingDate": "DATE",
    "hourEnding": "INTEGER",
    "totalResourceMWZoneSouth": "INTEGER",
    "totalResourceMWZoneNorth": "INTEGER",
    "totalResourceMWZoneWest": "INTEGER",
    "totalResourceMWZoneHouston": "INTEGER",
    "totalIRRMWZoneSouth": "INTEGER",
    "totalIRRMWZoneNorth": "INTEGER",
    "totalIRRMWZoneWest": "INTEGER",
    "totalIRRMWZoneHouston": "INTEGER",
    "totalNewEquipResourceMWZoneSouth": "INTEGER",
    "totalNewEquipResourceMWZoneNorth": "INTEGER",
    "totalNewEquipResourceMWZoneWest": "INTEGER",
    "totalNewEquipResourceMWZoneHouston": "INTEGER",
}


class Np3560Cd7dLoadFcastByFzn(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        postedDatetime: Source postedDatetime value.
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        north: Source north value.
        south: Source south value.
        west: Source west value.
        houston: Source houston value.
        systemTotal: Source systemTotal value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    postedDatetime: datetime
    deliveryDate: date
    hourEnding: StrictStr
    north: Decimal
    south: Decimal
    west: Decimal
    houston: Decimal
    systemTotal: Decimal
    DSTFlag: StrictBool


NP3_560_CD_7D_LOAD_FCAST_BY_FZN_FIELDS = {
    "postedDatetime": "DATETIME",
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "north": "DOUBLE",
    "south": "DOUBLE",
    "west": "DOUBLE",
    "houston": "DOUBLE",
    "systemTotal": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}


class Np3561Cd7dLoadFcastByWzn(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        postedDatetime: Source postedDatetime value.
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        coast: Source coast value.
        east: Source east value.
        farWest: Source farWest value.
        north: Source north value.
        northCentral: Source northCentral value.
        southCentral: Source southCentral value.
        southern: Source southern value.
        west: Source west value.
        systemTotal: Source systemTotal value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    postedDatetime: datetime
    deliveryDate: date
    hourEnding: StrictStr
    coast: Decimal
    east: Decimal
    farWest: Decimal
    north: Decimal
    northCentral: Decimal
    southCentral: Decimal
    southern: Decimal
    west: Decimal
    systemTotal: Decimal
    DSTFlag: StrictBool


NP3_561_CD_7D_LOAD_FCAST_BY_WZN_FIELDS = {
    "postedDatetime": "DATETIME",
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "coast": "DOUBLE",
    "east": "DOUBLE",
    "farWest": "DOUBLE",
    "north": "DOUBLE",
    "northCentral": "DOUBLE",
    "southCentral": "DOUBLE",
    "southern": "DOUBLE",
    "west": "DOUBLE",
    "systemTotal": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}


class Np3562CdIhLoadFcastByWzn(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        postedDatetime: Source postedDatetime value.
        intervalEnding: Source intervalEnding value.
        coast: Source coast value.
        east: Source east value.
        farWest: Source farWest value.
        north: Source north value.
        northCentral: Source northCentral value.
        southCentral: Source southCentral value.
        southern: Source southern value.
        west: Source west value.
        systemTotal: Source systemTotal value.
        model: Source model value.
        inUseFlag: Source inUseFlag value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    postedDatetime: datetime
    intervalEnding: datetime
    coast: Decimal
    east: Decimal
    farWest: Decimal
    north: Decimal
    northCentral: Decimal
    southCentral: Decimal
    southern: Decimal
    west: Decimal
    systemTotal: Decimal
    model: StrictStr
    inUseFlag: StrictBool
    DSTFlag: StrictBool


NP3_562_CD_IH_LOAD_FCAST_BY_WZN_FIELDS = {
    "postedDatetime": "DATETIME",
    "intervalEnding": "DATETIME",
    "coast": "DOUBLE",
    "east": "DOUBLE",
    "farWest": "DOUBLE",
    "north": "DOUBLE",
    "northCentral": "DOUBLE",
    "southCentral": "DOUBLE",
    "southern": "DOUBLE",
    "west": "DOUBLE",
    "systemTotal": "DOUBLE",
    "model": "VARCHAR",
    "inUseFlag": "BOOLEAN",
    "DSTFlag": "BOOLEAN",
}


class Np3565CdLfByModelWeatherZone(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        postedDatetime: Source postedDatetime value.
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        coast: Source coast value.
        east: Source east value.
        farWest: Source farWest value.
        north: Source north value.
        northCentral: Source northCentral value.
        southCentral: Source southCentral value.
        southern: Source southern value.
        west: Source west value.
        systemTotal: Source systemTotal value.
        model: Source model value.
        inUseFlag: Source inUseFlag value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    postedDatetime: datetime
    deliveryDate: date
    hourEnding: StrictStr
    coast: Decimal
    east: Decimal
    farWest: Decimal
    north: Decimal
    northCentral: Decimal
    southCentral: Decimal
    southern: Decimal
    west: Decimal
    systemTotal: Decimal
    model: StrictStr
    inUseFlag: StrictBool
    DSTFlag: StrictBool


NP3_565_CD_LF_BY_MODEL_WEATHER_ZONE_FIELDS = {
    "postedDatetime": "DATETIME",
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "coast": "DOUBLE",
    "east": "DOUBLE",
    "farWest": "DOUBLE",
    "north": "DOUBLE",
    "northCentral": "DOUBLE",
    "southCentral": "DOUBLE",
    "southern": "DOUBLE",
    "west": "DOUBLE",
    "systemTotal": "DOUBLE",
    "model": "VARCHAR",
    "inUseFlag": "BOOLEAN",
    "DSTFlag": "BOOLEAN",
}


class Np4158SgDamEssps(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        postedDatetime: Source postedDatetime value.
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        settlementPoint: Source hub, zone, or resource-node identifier.
        groupIndex: Source groupIndex value.
        updateTime: Source updateTime value.
        repeatHourFlag: Source repeatHourFlag value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    postedDatetime: datetime
    deliveryDate: date
    hourEnding: StrictStr
    settlementPoint: StrictStr
    groupIndex: StrictInt
    updateTime: datetime
    repeatHourFlag: StrictBool


NP4_158_SG_DAM_ESSPS_FIELDS = {
    "postedDatetime": "DATETIME",
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "settlementPoint": "VARCHAR",
    "groupIndex": "INTEGER",
    "updateTime": "DATETIME",
    "repeatHourFlag": "BOOLEAN",
}


class Np4159CdLoadDistributionFactors(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        postedDatetime: Source postedDatetime value.
        LDFDate: Source LDFDate value.
        LDFHour: Source LDFHour value.
        substation: Source substation value.
        distributionFactor: Source distributionFactor value.
        loadId: Source loadId value.
        MVARDistributionFactor: Source MVARDistributionFactor value.
        MRIDLoad: Source MRIDLoad value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    postedDatetime: datetime
    LDFDate: date
    LDFHour: StrictStr
    substation: StrictStr
    distributionFactor: Decimal
    loadId: StrictStr
    MVARDistributionFactor: Decimal
    MRIDLoad: StrictStr
    DSTFlag: StrictBool


NP4_159_CD_LOAD_DISTRIBUTION_FACTORS_FIELDS = {
    "postedDatetime": "DATETIME",
    "LDFDate": "DATE",
    "LDFHour": "VARCHAR",
    "substation": "VARCHAR",
    "distributionFactor": "DOUBLE",
    "loadId": "VARCHAR",
    "MVARDistributionFactor": "DOUBLE",
    "MRIDLoad": "VARCHAR",
    "DSTFlag": "BOOLEAN",
}


class Np4183CdDamHourlyLmp(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        busName: Source busName value.
        LMP: Source LMP value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictStr
    busName: StrictStr
    LMP: Decimal
    DSTFlag: StrictBool


NP4_183_CD_DAM_HOURLY_LMP_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "busName": "VARCHAR",
    "LMP": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}


class Np419CdDamAggAsOfferCurve(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        ancillaryType: Source ancillary-service identifier.
        price: Source price value.
        quantity: Source quantity value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictStr
    ancillaryType: StrictStr
    price: Decimal
    quantity: Decimal
    DSTFlag: StrictBool


NP4_19_CD_DAM_AGG_AS_OFFER_CURVE_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "ancillaryType": "VARCHAR",
    "price": "DOUBLE",
    "quantity": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}


class Np4191CdDamShadowPrices(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        constraintId: Source constraintId value.
        constraintName: Source constraintName value.
        contingencyName: Source contingencyName value.
        constraintLimit: Source constraintLimit value.
        constraintValue: Source constraintValue value.
        violationAmount: Source violationAmount value.
        shadowPrice: Source shadowPrice value.
        fromStation: Source fromStation value.
        toStation: Source toStation value.
        fromStationkV: Source fromStationkV value.
        toStationkV: Source toStationkV value.
        deliveryTime: Source deliveryTime value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictStr
    constraintId: StrictInt
    constraintName: StrictStr
    contingencyName: StrictStr
    constraintLimit: StrictInt
    constraintValue: StrictInt
    violationAmount: StrictInt
    shadowPrice: Decimal
    fromStation: StrictStr
    toStation: StrictStr
    fromStationkV: Decimal
    toStationkV: Decimal
    deliveryTime: datetime
    DSTFlag: StrictBool


NP4_191_CD_DAM_SHADOW_PRICES_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "constraintId": "INTEGER",
    "constraintName": "VARCHAR",
    "contingencyName": "VARCHAR",
    "constraintLimit": "INTEGER",
    "constraintValue": "INTEGER",
    "violationAmount": "INTEGER",
    "shadowPrice": "DOUBLE",
    "fromStation": "VARCHAR",
    "toStation": "VARCHAR",
    "fromStationkV": "DOUBLE",
    "toStationkV": "DOUBLE",
    "deliveryTime": "DATETIME",
    "DSTFlag": "BOOLEAN",
}


class Np4192CdDamTotalEnergyPurchased(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        settlementPoint: Source hub, zone, or resource-node identifier.
        totalDamEnergyBought: Source totalDamEnergyBought value.
        repeatHourFlag: Source repeatHourFlag value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictStr
    settlementPoint: StrictStr
    totalDamEnergyBought: Decimal
    repeatHourFlag: StrictBool


NP4_192_CD_DAM_TOTAL_ENERGY_PURCHASED_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "settlementPoint": "VARCHAR",
    "totalDamEnergyBought": "DOUBLE",
    "repeatHourFlag": "BOOLEAN",
}


class Np4193CdTotalDamEnergySold(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        settlementPoint: Source hub, zone, or resource-node identifier.
        totalDAMEnergySold: Source totalDAMEnergySold value.
        repeatHourFlag: Source repeatHourFlag value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictStr
    settlementPoint: StrictStr
    totalDAMEnergySold: Decimal
    repeatHourFlag: StrictBool


NP4_193_CD_TOTAL_DAM_ENERGY_SOLD_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "settlementPoint": "VARCHAR",
    "totalDAMEnergySold": "DOUBLE",
    "repeatHourFlag": "BOOLEAN",
}


class Np4194CdDamPtpObligationSpResults(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        stlPnt: Source stlPnt value.
        totalPtpOblAwardedSource: Source totalPtpOblAwardedSource value.
        totalPtpOblAwardedSink: Source totalPtpOblAwardedSink value.
        repeatedHourFlag: Source repeatedHourFlag value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictStr
    stlPnt: StrictStr
    totalPtpOblAwardedSource: Decimal
    totalPtpOblAwardedSink: Decimal
    repeatedHourFlag: StrictBool


NP4_194_CD_DAM_PTP_OBLIGATION_SP_RESULTS_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "stlPnt": "VARCHAR",
    "totalPtpOblAwardedSource": "DOUBLE",
    "totalPtpOblAwardedSink": "DOUBLE",
    "repeatedHourFlag": "BOOLEAN",
}


class Np4196MDamPriceCorrectionsEblmp(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        deliveryHour: Source deliveryHour value.
        electricalBus: Source electricalBus value.
        LMPOriginal: Source LMPOriginal value.
        LMPCorrected: Source LMPCorrected value.
        priceCorrectionTime: Source priceCorrectionTime value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    deliveryHour: StrictInt
    electricalBus: StrictStr
    LMPOriginal: Decimal
    LMPCorrected: Decimal
    priceCorrectionTime: datetime
    DSTFlag: StrictBool


NP4_196_M_DAM_PRICE_CORRECTIONS_EBLMP_FIELDS = {
    "deliveryDate": "DATE",
    "deliveryHour": "INTEGER",
    "electricalBus": "VARCHAR",
    "LMPOriginal": "DOUBLE",
    "LMPCorrected": "DOUBLE",
    "priceCorrectionTime": "DATETIME",
    "DSTFlag": "BOOLEAN",
}


class Np4196MDamPriceCorrectionsMcpc(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        deliveryHour: Source deliveryHour value.
        ASType: Source ASType value.
        MCPCOriginal: Source MCPCOriginal value.
        MCPCCorrected: Source MCPCCorrected value.
        priceCorrectionTime: Source priceCorrectionTime value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    deliveryHour: StrictInt
    ASType: StrictStr
    MCPCOriginal: Decimal
    MCPCCorrected: Decimal
    priceCorrectionTime: datetime
    DSTFlag: StrictBool


NP4_196_M_DAM_PRICE_CORRECTIONS_MCPC_FIELDS = {
    "deliveryDate": "DATE",
    "deliveryHour": "INTEGER",
    "ASType": "VARCHAR",
    "MCPCOriginal": "DOUBLE",
    "MCPCCorrected": "DOUBLE",
    "priceCorrectionTime": "DATETIME",
    "DSTFlag": "BOOLEAN",
}


class Np4196MDamPriceCorrectionsSpp(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        deliveryHour: Source deliveryHour value.
        settlementPoint: Source hub, zone, or resource-node identifier.
        SPPOriginal: Source SPPOriginal value.
        SPPCorrected: Source SPPCorrected value.
        priceCorrectionTime: Source priceCorrectionTime value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    deliveryHour: StrictInt
    settlementPoint: StrictStr
    SPPOriginal: Decimal
    SPPCorrected: Decimal
    priceCorrectionTime: datetime
    DSTFlag: StrictBool


NP4_196_M_DAM_PRICE_CORRECTIONS_SPP_FIELDS = {
    "deliveryDate": "DATE",
    "deliveryHour": "INTEGER",
    "settlementPoint": "VARCHAR",
    "SPPOriginal": "DOUBLE",
    "SPPCorrected": "DOUBLE",
    "priceCorrectionTime": "DATETIME",
    "DSTFlag": "BOOLEAN",
}


class Np4197MRtmPriceCorrectionsEblmp(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        SCEDTimestamp: Source SCEDTimestamp value.
        electricalBus: Source electricalBus value.
        cappedLMPOriginal: Source cappedLMPOriginal value.
        uncappedLMPOriginal: Source uncappedLMPOriginal value.
        cappedLMPCorrected: Source cappedLMPCorrected value.
        uncappedLMPCorrected: Source uncappedLMPCorrected value.
        priceCorrectionTime: Source priceCorrectionTime value.
        repeatedHourFlag: Source repeatedHourFlag value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    SCEDTimestamp: datetime
    electricalBus: StrictStr
    cappedLMPOriginal: Decimal
    uncappedLMPOriginal: Decimal | None
    cappedLMPCorrected: Decimal
    uncappedLMPCorrected: Decimal | None
    priceCorrectionTime: datetime
    repeatedHourFlag: StrictBool


NP4_197_M_RTM_PRICE_CORRECTIONS_EBLMP_FIELDS = {
    "SCEDTimestamp": "DATETIME",
    "electricalBus": "VARCHAR",
    "cappedLMPOriginal": "DOUBLE",
    "uncappedLMPOriginal": "DOUBLE",
    "cappedLMPCorrected": "DOUBLE",
    "uncappedLMPCorrected": "DOUBLE",
    "priceCorrectionTime": "DATETIME",
    "repeatedHourFlag": "BOOLEAN",
}


class Np4197MRtmPriceCorrectionsMcpcSced(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        SCEDTimestamp: Source SCEDTimestamp value.
        ASType: Source ASType value.
        cappedMCPCOriginal: Source cappedMCPCOriginal value.
        uncappedMCPCOriginal: Source uncappedMCPCOriginal value.
        cappedMCPCCorrected: Source cappedMCPCCorrected value.
        uncappedMCPCCorrected: Source uncappedMCPCCorrected value.
        priceCorrectionTime: Source priceCorrectionTime value.
        repeatedHourFlag: Source repeatedHourFlag value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    SCEDTimestamp: datetime
    ASType: StrictStr
    cappedMCPCOriginal: Decimal
    uncappedMCPCOriginal: Decimal | None
    cappedMCPCCorrected: Decimal
    uncappedMCPCCorrected: Decimal | None
    priceCorrectionTime: datetime
    repeatedHourFlag: StrictBool


NP4_197_M_RTM_PRICE_CORRECTIONS_MCPC_SCED_FIELDS = {
    "SCEDTimestamp": "DATETIME",
    "ASType": "VARCHAR",
    "cappedMCPCOriginal": "DOUBLE",
    "uncappedMCPCOriginal": "DOUBLE",
    "cappedMCPCCorrected": "DOUBLE",
    "uncappedMCPCCorrected": "DOUBLE",
    "priceCorrectionTime": "DATETIME",
    "repeatedHourFlag": "BOOLEAN",
}


class Np4197MRtmPriceCorrectionsMcpcSpp(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        deliveryHour: Source deliveryHour value.
        deliveryInterval: Source deliveryInterval value.
        ASType: Source ASType value.
        MCPCOriginal: Source MCPCOriginal value.
        MCPCCorrected: Source MCPCCorrected value.
        priceCorrectionTime: Source priceCorrectionTime value.
        repeatHourFlag: Source repeatHourFlag value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    deliveryHour: StrictInt
    deliveryInterval: StrictInt
    ASType: StrictStr
    MCPCOriginal: Decimal
    MCPCCorrected: Decimal
    priceCorrectionTime: datetime
    repeatHourFlag: StrictBool


NP4_197_M_RTM_PRICE_CORRECTIONS_MCPC_SPP_FIELDS = {
    "deliveryDate": "DATE",
    "deliveryHour": "INTEGER",
    "deliveryInterval": "INTEGER",
    "ASType": "VARCHAR",
    "MCPCOriginal": "DOUBLE",
    "MCPCCorrected": "DOUBLE",
    "priceCorrectionTime": "DATETIME",
    "repeatHourFlag": "BOOLEAN",
}


class Np4197MRtmPriceCorrectionsShadow(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        SCEDTimestamp: Source SCEDTimestamp value.
        constraintId: Source constraintId value.
        constraintName: Source constraintName value.
        contingencyName: Source contingencyName value.
        shadowPriceOriginal: Source shadowPriceOriginal value.
        shadowPriceCorrected: Source shadowPriceCorrected value.
        limitOriginal: Source limitOriginal value.
        limitCorrected: Source limitCorrected value.
        valueOriginal: Source valueOriginal value.
        valueCorrected: Source valueCorrected value.
        priceCorrectionTime: Source priceCorrectionTime value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    SCEDTimestamp: datetime
    constraintId: StrictInt
    constraintName: StrictStr
    contingencyName: StrictStr
    shadowPriceOriginal: Decimal
    shadowPriceCorrected: Decimal
    limitOriginal: Decimal
    limitCorrected: Decimal
    valueOriginal: Decimal
    valueCorrected: Decimal
    priceCorrectionTime: datetime
    DSTFlag: StrictBool


NP4_197_M_RTM_PRICE_CORRECTIONS_SHADOW_FIELDS = {
    "SCEDTimestamp": "DATETIME",
    "constraintId": "INTEGER",
    "constraintName": "VARCHAR",
    "contingencyName": "VARCHAR",
    "shadowPriceOriginal": "DOUBLE",
    "shadowPriceCorrected": "DOUBLE",
    "limitOriginal": "DOUBLE",
    "limitCorrected": "DOUBLE",
    "valueOriginal": "DOUBLE",
    "valueCorrected": "DOUBLE",
    "priceCorrectionTime": "DATETIME",
    "DSTFlag": "BOOLEAN",
}


class Np4197MRtmPriceCorrectionsSoglmp(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        SCEDTimestamp: Source SCEDTimestamp value.
        resourceType: Source resourceType value.
        resourceName: Source resourceName value.
        meterName: Source meterName value.
        meterLMPOriginal: Source meterLMPOriginal value.
        meterLMPCorrected: Source meterLMPCorrected value.
        RTRDPAOriginal: Source RTRDPAOriginal value.
        RTRDPACorrected: Source RTRDPACorrected value.
        finalLMPOriginal: Source finalLMPOriginal value.
        finalLMPCorrected: Source finalLMPCorrected value.
        priceCorrectionTime: Source priceCorrectionTime value.
        repeatHourFlag: Source repeatHourFlag value.
        RTORPAOriginal: Source RTORPAOriginal value.
        RTORPACorrected: Source RTORPACorrected value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    SCEDTimestamp: datetime
    resourceType: StrictStr
    resourceName: StrictStr
    meterName: StrictStr
    meterLMPOriginal: Decimal
    meterLMPCorrected: Decimal
    RTRDPAOriginal: Decimal
    RTRDPACorrected: Decimal
    finalLMPOriginal: Decimal
    finalLMPCorrected: Decimal
    priceCorrectionTime: datetime
    repeatHourFlag: StrictBool
    RTORPAOriginal: Decimal | None
    RTORPACorrected: Decimal | None


NP4_197_M_RTM_PRICE_CORRECTIONS_SOGLMP_FIELDS = {
    "SCEDTimestamp": "DATETIME",
    "resourceType": "VARCHAR",
    "resourceName": "VARCHAR",
    "meterName": "VARCHAR",
    "meterLMPOriginal": "DOUBLE",
    "meterLMPCorrected": "DOUBLE",
    "RTRDPAOriginal": "DOUBLE",
    "RTRDPACorrected": "DOUBLE",
    "finalLMPOriginal": "DOUBLE",
    "finalLMPCorrected": "DOUBLE",
    "priceCorrectionTime": "DATETIME",
    "repeatHourFlag": "BOOLEAN",
    "RTORPAOriginal": "DOUBLE",
    "RTORPACorrected": "DOUBLE",
}


class Np4197MRtmPriceCorrectionsSogprice(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        deliveryHour: Source deliveryHour value.
        deliveryInterval: Source deliveryInterval value.
        resourceType: Source resourceType value.
        resourceName: Source resourceName value.
        meterName: Source meterName value.
        priceOriginal: Source priceOriginal value.
        priceCorrected: Source priceCorrected value.
        priceCorrectionTime: Source priceCorrectionTime value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    deliveryHour: StrictInt
    deliveryInterval: StrictInt
    resourceType: StrictStr
    resourceName: StrictStr
    meterName: StrictStr
    priceOriginal: Decimal
    priceCorrected: Decimal
    priceCorrectionTime: datetime
    DSTFlag: StrictBool


NP4_197_M_RTM_PRICE_CORRECTIONS_SOGPRICE_FIELDS = {
    "deliveryDate": "DATE",
    "deliveryHour": "INTEGER",
    "deliveryInterval": "INTEGER",
    "resourceType": "VARCHAR",
    "resourceName": "VARCHAR",
    "meterName": "VARCHAR",
    "priceOriginal": "DOUBLE",
    "priceCorrected": "DOUBLE",
    "priceCorrectionTime": "DATETIME",
    "DSTFlag": "BOOLEAN",
}


class Np4197MRtmPriceCorrectionsSplmp(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        SCEDTimestamp: Source SCEDTimestamp value.
        settlementPointName: Source settlementPointName value.
        LMPOriginal: Source LMPOriginal value.
        LMPCorrected: Source LMPCorrected value.
        priceCorrectionTime: Source priceCorrectionTime value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    SCEDTimestamp: datetime
    settlementPointName: StrictStr
    LMPOriginal: Decimal
    LMPCorrected: Decimal
    priceCorrectionTime: datetime
    DSTFlag: StrictBool


NP4_197_M_RTM_PRICE_CORRECTIONS_SPLMP_FIELDS = {
    "SCEDTimestamp": "DATETIME",
    "settlementPointName": "VARCHAR",
    "LMPOriginal": "DOUBLE",
    "LMPCorrected": "DOUBLE",
    "priceCorrectionTime": "DATETIME",
    "DSTFlag": "BOOLEAN",
}


class Np4197MRtmPriceCorrectionsSpp(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        deliveryHour: Source deliveryHour value.
        deliveryInterval: Source deliveryInterval value.
        settlementPointName: Source settlementPointName value.
        settlementPointType: Source settlementPointType value.
        SPPOriginal: Source SPPOriginal value.
        SPPCorrected: Source SPPCorrected value.
        priceCorrectionTime: Source priceCorrectionTime value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    deliveryHour: StrictInt
    deliveryInterval: StrictInt
    settlementPointName: StrictStr
    settlementPointType: StrictStr
    SPPOriginal: Decimal
    SPPCorrected: Decimal
    priceCorrectionTime: datetime
    DSTFlag: StrictBool


NP4_197_M_RTM_PRICE_CORRECTIONS_SPP_FIELDS = {
    "deliveryDate": "DATE",
    "deliveryHour": "INTEGER",
    "deliveryInterval": "INTEGER",
    "settlementPointName": "VARCHAR",
    "settlementPointType": "VARCHAR",
    "SPPOriginal": "DOUBLE",
    "SPPCorrected": "DOUBLE",
    "priceCorrectionTime": "DATETIME",
    "DSTFlag": "BOOLEAN",
}


class Np4200CdDamDeEnergizedSpbc(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        settlementPoint: Source hub, zone, or resource-node identifier.
        repeatedHourFlag: Source repeatedHourFlag value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictStr
    settlementPoint: StrictStr
    repeatedHourFlag: StrictBool


NP4_200_CD_DAM_DE_ENERGIZED_SPBC_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "settlementPoint": "VARCHAR",
    "repeatedHourFlag": "BOOLEAN",
}


class Np4212CdDamScedAsDemandCurves(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        postedDatetime: Source postedDatetime value.
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        ASType: Source ASType value.
        demandCurvePoint: Source demandCurvePoint value.
        quantity: Source quantity value.
        price: Source price value.
        repeatHourFlag: Source repeatHourFlag value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    postedDatetime: datetime
    deliveryDate: date
    hourEnding: StrictStr
    ASType: StrictStr
    demandCurvePoint: Decimal
    quantity: Decimal
    price: Decimal
    repeatHourFlag: StrictBool


NP4_212_CD_DAM_SCED_AS_DEMAND_CURVES_FIELDS = {
    "postedDatetime": "DATETIME",
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "ASType": "VARCHAR",
    "demandCurvePoint": "DOUBLE",
    "quantity": "DOUBLE",
    "price": "DOUBLE",
    "repeatHourFlag": "BOOLEAN",
}


class Np4213CdHrucAsDemandCurves(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        RUCTimestamp: Source RUCTimestamp value.
        ASType: Source ASType value.
        demandCurvePoint: Source demandCurvePoint value.
        quantity: Source quantity value.
        price: Source price value.
        repeatHourFlag: Source repeatHourFlag value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictStr
    RUCTimestamp: datetime
    ASType: StrictStr
    demandCurvePoint: Decimal
    quantity: Decimal
    price: Decimal
    repeatHourFlag: StrictBool


NP4_213_CD_HRUC_AS_DEMAND_CURVES_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "RUCTimestamp": "DATETIME",
    "ASType": "VARCHAR",
    "demandCurvePoint": "DOUBLE",
    "quantity": "DOUBLE",
    "price": "DOUBLE",
    "repeatHourFlag": "BOOLEAN",
}


class Np4214CdDrucAsDemandCurves(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        RUCTimestamp: Source RUCTimestamp value.
        ASType: Source ASType value.
        demandCurvePoint: Source demandCurvePoint value.
        quantity: Source quantity value.
        price: Source price value.
        repeatHourFlag: Source repeatHourFlag value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictStr
    RUCTimestamp: datetime
    ASType: StrictStr
    demandCurvePoint: Decimal
    quantity: Decimal
    price: Decimal
    repeatHourFlag: StrictBool


NP4_214_CD_DRUC_AS_DEMAND_CURVES_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "RUCTimestamp": "DATETIME",
    "ASType": "VARCHAR",
    "demandCurvePoint": "DOUBLE",
    "quantity": "DOUBLE",
    "price": "DOUBLE",
    "repeatHourFlag": "BOOLEAN",
}


class Np4215CdWrucAsDemandCurves(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        postedDatetime: Source postedDatetime value.
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        RUCTimestamp: Source RUCTimestamp value.
        ASType: Source ASType value.
        demandCurvePoint: Source demandCurvePoint value.
        quantity: Source quantity value.
        price: Source price value.
        repeatHourFlag: Source repeatHourFlag value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    postedDatetime: datetime
    deliveryDate: date
    hourEnding: StrictStr
    RUCTimestamp: datetime
    ASType: StrictStr
    demandCurvePoint: Decimal
    quantity: Decimal
    price: Decimal
    repeatHourFlag: StrictBool


NP4_215_CD_WRUC_AS_DEMAND_CURVES_FIELDS = {
    "postedDatetime": "DATETIME",
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "RUCTimestamp": "DATETIME",
    "ASType": "VARCHAR",
    "demandCurvePoint": "DOUBLE",
    "quantity": "DOUBLE",
    "price": "DOUBLE",
    "repeatHourFlag": "BOOLEAN",
}


class Np4231CdElectricalBusMapHeurPrice(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        postedDatetime: Source postedDatetime value.
        marketType: Source marketType value.
        fromEBName: Source fromEBName value.
        toEBName: Source toEBName value.
        type: Source type value.
        priority: Source priority value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    postedDatetime: datetime
    marketType: StrictStr
    fromEBName: StrictStr
    toEBName: StrictStr
    type: StrictStr
    priority: Decimal


NP4_231_CD_ELECTRICAL_BUS_MAP_HEUR_PRICE_FIELDS = {
    "postedDatetime": "DATETIME",
    "marketType": "VARCHAR",
    "fromEBName": "VARCHAR",
    "toEBName": "VARCHAR",
    "type": "VARCHAR",
    "priority": "DOUBLE",
}


class Np433CdDamAsPlan(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        postedDatetime: Source postedDatetime value.
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        ancillaryType: Source ancillary-service identifier.
        quantity: Source quantity value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    postedDatetime: datetime
    deliveryDate: date
    hourEnding: StrictStr
    ancillaryType: StrictStr
    quantity: StrictInt
    DSTFlag: StrictBool


NP4_33_CD_DAM_AS_PLAN_FIELDS = {
    "postedDatetime": "DATETIME",
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "ancillaryType": "VARCHAR",
    "quantity": "INTEGER",
    "DSTFlag": "BOOLEAN",
}


class Np4523CdDamSystemLambda(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        systemLambda: Source systemLambda value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictStr
    systemLambda: Decimal
    DSTFlag: StrictBool


NP4_523_CD_DAM_SYSTEM_LAMBDA_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "systemLambda": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}


class Np6322CdScedSystemLambda(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        SCEDTimestamp: Source SCEDTimestamp value.
        repeatedHourFlag: Source repeatedHourFlag value.
        cappedSystemLambda: Source cappedSystemLambda value.
        uncappedSystemLambda: Source uncappedSystemLambda value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    SCEDTimestamp: datetime
    repeatedHourFlag: StrictBool
    cappedSystemLambda: Decimal
    uncappedSystemLambda: Decimal | None


NP6_322_CD_SCED_SYSTEM_LAMBDA_FIELDS = {
    "SCEDTimestamp": "DATETIME",
    "repeatedHourFlag": "BOOLEAN",
    "cappedSystemLambda": "DOUBLE",
    "uncappedSystemLambda": "DOUBLE",
}


class Np6323CdRtPriceAdderSced(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        SCEDTimestamp: Source SCEDTimestamp value.
        repeatHourFlag: Source repeatHourFlag value.
        systemLambda: Source systemLambda value.
        RTRDPA: Source RTRDPA value.
        RTRDPARUS: Source RTRDPARUS value.
        RTRDPARDS: Source RTRDPARDS value.
        RTRDPARRS: Source RTRDPARRS value.
        RTRDPAECRS: Source RTRDPAECRS value.
        RTRDPANSS: Source RTRDPANSS value.
        RTRRUC: Source RTRRUC value.
        RTRRMR: Source RTRRMR value.
        RTDNCLR: Source RTDNCLR value.
        RTDERS: Source RTDERS value.
        RTDCTIEIMPORT: Source RTDCTIEIMPORT value.
        RTDCTIEEXPORT: Source RTDCTIEEXPORT value.
        RTBLTIMPORT: Source RTBLTIMPORT value.
        RTBLTEXPORT: Source RTBLTEXPORT value.
        RTOLLSL: Source RTOLLSL value.
        RTOLHSL: Source RTOLHSL value.
        RTDLL: Source RTDLL value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    SCEDTimestamp: datetime
    repeatHourFlag: StrictBool
    systemLambda: Decimal
    RTRDPA: Decimal
    RTRDPARUS: Decimal
    RTRDPARDS: Decimal
    RTRDPARRS: Decimal
    RTRDPAECRS: Decimal
    RTRDPANSS: Decimal
    RTRRUC: Decimal
    RTRRMR: Decimal
    RTDNCLR: Decimal
    RTDERS: Decimal
    RTDCTIEIMPORT: Decimal
    RTDCTIEEXPORT: Decimal
    RTBLTIMPORT: Decimal
    RTBLTEXPORT: Decimal
    RTOLLSL: Decimal
    RTOLHSL: Decimal
    RTDLL: Decimal | None


NP6_323_CD_RT_PRICE_ADDER_SCED_FIELDS = {
    "SCEDTimestamp": "DATETIME",
    "repeatHourFlag": "BOOLEAN",
    "systemLambda": "DOUBLE",
    "RTRDPA": "DOUBLE",
    "RTRDPARUS": "DOUBLE",
    "RTRDPARDS": "DOUBLE",
    "RTRDPARRS": "DOUBLE",
    "RTRDPAECRS": "DOUBLE",
    "RTRDPANSS": "DOUBLE",
    "RTRRUC": "DOUBLE",
    "RTRRMR": "DOUBLE",
    "RTDNCLR": "DOUBLE",
    "RTDERS": "DOUBLE",
    "RTDCTIEIMPORT": "DOUBLE",
    "RTDCTIEEXPORT": "DOUBLE",
    "RTBLTIMPORT": "DOUBLE",
    "RTBLTEXPORT": "DOUBLE",
    "RTOLLSL": "DOUBLE",
    "RTOLHSL": "DOUBLE",
    "RTDLL": "DOUBLE",
}


class Np6324CdRt15minPriceAdders(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        deliveryHour: Source deliveryHour value.
        deliveryInterval: Source deliveryInterval value.
        RTRDPA: Source RTRDPA value.
        RTRDPRU: Source RTRDPRU value.
        RTRDPRD: Source RTRDPRD value.
        RTRDPRRS: Source RTRDPRRS value.
        RTRDPECRS: Source RTRDPECRS value.
        RTRDPNS: Source RTRDPNS value.
        repeatHourFlag: Source repeatHourFlag value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    deliveryHour: StrictInt
    deliveryInterval: StrictInt
    RTRDPA: Decimal
    RTRDPRU: Decimal
    RTRDPRD: Decimal
    RTRDPRRS: Decimal
    RTRDPECRS: Decimal
    RTRDPNS: Decimal
    repeatHourFlag: StrictBool


NP6_324_CD_RT_15MIN_PRICE_ADDERS_FIELDS = {
    "deliveryDate": "DATE",
    "deliveryHour": "INTEGER",
    "deliveryInterval": "INTEGER",
    "RTRDPA": "DOUBLE",
    "RTRDPRU": "DOUBLE",
    "RTRDPRD": "DOUBLE",
    "RTRDPRRS": "DOUBLE",
    "RTRDPECRS": "DOUBLE",
    "RTRDPNS": "DOUBLE",
    "repeatHourFlag": "BOOLEAN",
}


class Np6325CdRtdPriceAdders(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        RTDTimestamp: Source RTDTimestamp value.
        repeatHourFlag: Source repeatHourFlag value.
        intervalID: Source intervalID value.
        intervalEnding: Source intervalEnding value.
        IERepeatHourFlag: Source IERepeatHourFlag value.
        systemLambda: Source systemLambda value.
        RTRDPA: Source RTRDPA value.
        RTRDPARUS: Source RTRDPARUS value.
        RTRDPARDS: Source RTRDPARDS value.
        RTRDPARRS: Source RTRDPARRS value.
        RTRDPAECRS: Source RTRDPAECRS value.
        RTRDPANSS: Source RTRDPANSS value.
        RTRRUC: Source RTRRUC value.
        RTRRMR: Source RTRRMR value.
        RTDNCLR: Source RTDNCLR value.
        RTDERS: Source RTDERS value.
        RTDCTIEImport: Source RTDCTIEImport value.
        RTDCTIEExport: Source RTDCTIEExport value.
        RTBLTImport: Source RTBLTImport value.
        RTBLTExport: Source RTBLTExport value.
        RTOLLSL: Source RTOLLSL value.
        RTOLHSL: Source RTOLHSL value.
        RTDLL: Source RTDLL value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    RTDTimestamp: datetime
    repeatHourFlag: StrictBool
    intervalID: StrictInt
    intervalEnding: datetime
    IERepeatHourFlag: StrictBool
    systemLambda: Decimal
    RTRDPA: Decimal
    RTRDPARUS: Decimal
    RTRDPARDS: Decimal
    RTRDPARRS: Decimal
    RTRDPAECRS: Decimal
    RTRDPANSS: Decimal
    RTRRUC: Decimal
    RTRRMR: Decimal
    RTDNCLR: Decimal
    RTDERS: Decimal
    RTDCTIEImport: Decimal
    RTDCTIEExport: Decimal
    RTBLTImport: Decimal
    RTBLTExport: Decimal
    RTOLLSL: Decimal
    RTOLHSL: Decimal
    RTDLL: Decimal | None


NP6_325_CD_RTD_PRICE_ADDERS_FIELDS = {
    "RTDTimestamp": "DATETIME",
    "repeatHourFlag": "BOOLEAN",
    "intervalID": "INTEGER",
    "intervalEnding": "DATETIME",
    "IERepeatHourFlag": "BOOLEAN",
    "systemLambda": "DOUBLE",
    "RTRDPA": "DOUBLE",
    "RTRDPARUS": "DOUBLE",
    "RTRDPARDS": "DOUBLE",
    "RTRDPARRS": "DOUBLE",
    "RTRDPAECRS": "DOUBLE",
    "RTRDPANSS": "DOUBLE",
    "RTRRUC": "DOUBLE",
    "RTRRMR": "DOUBLE",
    "RTDNCLR": "DOUBLE",
    "RTDERS": "DOUBLE",
    "RTDCTIEImport": "DOUBLE",
    "RTDCTIEExport": "DOUBLE",
    "RTBLTImport": "DOUBLE",
    "RTBLTExport": "DOUBLE",
    "RTOLLSL": "DOUBLE",
    "RTOLHSL": "DOUBLE",
    "RTDLL": "DOUBLE",
}


class Np6326CdRtPriceSog(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        deliveryHour: Source deliveryHour value.
        deliveryInterval: Source deliveryInterval value.
        resourceType: Source resourceType value.
        resourceName: Source resourceName value.
        meterName: Source meterName value.
        meterPrice: Source meterPrice value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    deliveryHour: StrictInt
    deliveryInterval: StrictInt
    resourceType: StrictStr
    resourceName: StrictStr
    meterName: StrictStr
    meterPrice: Decimal
    DSTFlag: StrictBool


NP6_326_CD_RT_PRICE_SOG_FIELDS = {
    "deliveryDate": "DATE",
    "deliveryHour": "INTEGER",
    "deliveryInterval": "INTEGER",
    "resourceType": "VARCHAR",
    "resourceName": "VARCHAR",
    "meterName": "VARCHAR",
    "meterPrice": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}


class Np6327CdLmpSogPriceAdders(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        SCEDTimestamp: Source SCEDTimestamp value.
        repeatHourFlag: Source repeatHourFlag value.
        resourceType: Source resourceType value.
        resourceName: Source resourceName value.
        stationName: Source stationName value.
        voltageLevel: Source voltageLevel value.
        meterName: Source meterName value.
        meterLMP: Source meterLMP value.
        RTRDPA: Source RTRDPA value.
        finalLMP: Source finalLMP value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    SCEDTimestamp: datetime
    repeatHourFlag: StrictBool
    resourceType: StrictStr
    resourceName: StrictStr
    stationName: StrictStr
    voltageLevel: Decimal
    meterName: StrictStr
    meterLMP: Decimal
    RTRDPA: Decimal
    finalLMP: Decimal


NP6_327_CD_LMP_SOG_PRICE_ADDERS_FIELDS = {
    "SCEDTimestamp": "DATETIME",
    "repeatHourFlag": "BOOLEAN",
    "resourceType": "VARCHAR",
    "resourceName": "VARCHAR",
    "stationName": "VARCHAR",
    "voltageLevel": "DOUBLE",
    "meterName": "VARCHAR",
    "meterLMP": "DOUBLE",
    "RTRDPA": "DOUBLE",
    "finalLMP": "DOUBLE",
}


class Np6328CdTotAsResCap(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        SCEDTimestamp: Source SCEDTimestamp value.
        repeatHourFlag: Source repeatHourFlag value.
        capREGUP: Source capREGUP value.
        capREGDN: Source capREGDN value.
        capRRS: Source capRRS value.
        capECRS: Source capECRS value.
        capNSPIN: Source capNSPIN value.
        capREGUPRRS: Source capREGUPRRS value.
        capREGUPRRSECRS: Source capREGUPRRSECRS value.
        capREGUPRRSECRSNSPIN: Source capREGUPRRSECRSNSPIN value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    SCEDTimestamp: datetime
    repeatHourFlag: StrictBool
    capREGUP: Decimal
    capREGDN: Decimal
    capRRS: Decimal
    capECRS: Decimal
    capNSPIN: Decimal
    capREGUPRRS: Decimal
    capREGUPRRSECRS: Decimal
    capREGUPRRSECRSNSPIN: Decimal


NP6_328_CD_TOT_AS_RES_CAP_FIELDS = {
    "SCEDTimestamp": "DATETIME",
    "repeatHourFlag": "BOOLEAN",
    "capREGUP": "DOUBLE",
    "capREGDN": "DOUBLE",
    "capRRS": "DOUBLE",
    "capECRS": "DOUBLE",
    "capNSPIN": "DOUBLE",
    "capREGUPRRS": "DOUBLE",
    "capREGUPRRSECRS": "DOUBLE",
    "capREGUPRRSECRSNSPIN": "DOUBLE",
}


class Np6329CdRtdIndMcpc(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        RTDTimestamp: Source RTDTimestamp value.
        repeatHourFlag: Source repeatHourFlag value.
        intervalId: Source intervalId value.
        intervalEnding: Source intervalEnding value.
        intervalRepeatHourFlag: Source intervalRepeatHourFlag value.
        REGUP: Source REGUP value.
        REGDN: Source REGDN value.
        RRS: Source RRS value.
        ECRS: Source ECRS value.
        NSPIN: Source NSPIN value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    RTDTimestamp: datetime
    repeatHourFlag: StrictBool
    intervalId: StrictInt
    intervalEnding: datetime
    intervalRepeatHourFlag: StrictBool
    REGUP: Decimal
    REGDN: Decimal
    RRS: Decimal
    ECRS: Decimal
    NSPIN: Decimal


NP6_329_CD_RTD_IND_MCPC_FIELDS = {
    "RTDTimestamp": "DATETIME",
    "repeatHourFlag": "BOOLEAN",
    "intervalId": "INTEGER",
    "intervalEnding": "DATETIME",
    "intervalRepeatHourFlag": "BOOLEAN",
    "REGUP": "DOUBLE",
    "REGDN": "DOUBLE",
    "RRS": "DOUBLE",
    "ECRS": "DOUBLE",
    "NSPIN": "DOUBLE",
}


class Np6331CdRtClearPriceCap(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        deliveryHour: Source deliveryHour value.
        deliveryInt: Source deliveryInt value.
        repeatHourFlag: Source repeatHourFlag value.
        ASType: Source ASType value.
        MCPC: Decimal source capacity clearing price.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    deliveryHour: StrictInt
    deliveryInt: StrictInt
    repeatHourFlag: StrictBool
    ASType: StrictStr
    MCPC: Decimal


NP6_331_CD_RT_CLEAR_PRICE_CAP_FIELDS = {
    "deliveryDate": "DATE",
    "deliveryHour": "INTEGER",
    "deliveryInt": "INTEGER",
    "repeatHourFlag": "BOOLEAN",
    "ASType": "VARCHAR",
    "MCPC": "DOUBLE",
}


class Np6332CdRtClearPriceCapSced(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        SCEDTimestamp: Source SCEDTimestamp value.
        repeatedHourFlag: Source repeatedHourFlag value.
        ASType: Source ASType value.
        cappedMCPC: Source cappedMCPC value.
        uncappedMCPC: Source uncappedMCPC value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    SCEDTimestamp: datetime
    repeatedHourFlag: StrictBool
    ASType: StrictStr
    cappedMCPC: Decimal
    uncappedMCPC: Decimal | None


NP6_332_CD_RT_CLEAR_PRICE_CAP_SCED_FIELDS = {
    "SCEDTimestamp": "DATETIME",
    "repeatedHourFlag": "BOOLEAN",
    "ASType": "VARCHAR",
    "cappedMCPC": "DOUBLE",
    "uncappedMCPC": "DOUBLE",
}


class Np6346CdActSysLoadByFzn(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        operatingDay: Source operatingDay value.
        hourEnding: Source hour-ending label, including 24:00.
        north: Source north value.
        south: Source south value.
        west: Source west value.
        houston: Source houston value.
        total: Source total value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    operatingDay: date
    hourEnding: StrictStr
    north: Decimal
    south: Decimal
    west: Decimal
    houston: Decimal
    total: Decimal
    DSTFlag: StrictBool


NP6_346_CD_ACT_SYS_LOAD_BY_FZN_FIELDS = {
    "operatingDay": "DATE",
    "hourEnding": "VARCHAR",
    "north": "DOUBLE",
    "south": "DOUBLE",
    "west": "DOUBLE",
    "houston": "DOUBLE",
    "total": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}


class Np6787CdLmpElectricalBus(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        SCEDTimestamp: Source SCEDTimestamp value.
        repeatedHourFlag: Source repeatedHourFlag value.
        electricalBus: Source electricalBus value.
        cappedLMP: Source cappedLMP value.
        uncappedLMP: Source uncappedLMP value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    SCEDTimestamp: datetime
    repeatedHourFlag: StrictBool
    electricalBus: StrictStr
    cappedLMP: Decimal
    uncappedLMP: Decimal


NP6_787_CD_LMP_ELECTRICAL_BUS_FIELDS = {
    "SCEDTimestamp": "DATETIME",
    "repeatedHourFlag": "BOOLEAN",
    "electricalBus": "VARCHAR",
    "cappedLMP": "DOUBLE",
    "uncappedLMP": "DOUBLE",
}


class Np6788CdLmpNodeZoneHub(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        SCEDTimestamp: Source SCEDTimestamp value.
        repeatHourFlag: Source repeatHourFlag value.
        settlementPoint: Source hub, zone, or resource-node identifier.
        LMP: Source LMP value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    SCEDTimestamp: datetime
    repeatHourFlag: StrictBool
    settlementPoint: StrictStr
    LMP: Decimal


NP6_788_CD_LMP_NODE_ZONE_HUB_FIELDS = {
    "SCEDTimestamp": "DATETIME",
    "repeatHourFlag": "BOOLEAN",
    "settlementPoint": "VARCHAR",
    "LMP": "DOUBLE",
}


class Np686CdShdwPricesBndTrnsConst(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        SCEDTimestamp: Source SCEDTimestamp value.
        repeatedHourFlag: Source repeatedHourFlag value.
        constraintID: Source constraintID value.
        constraintName: Source constraintName value.
        contingencyName: Source contingencyName value.
        shadowPrice: Source shadowPrice value.
        maxShadowPrice: Source maxShadowPrice value.
        limit: Source limit value.
        value: Source value value.
        violatedMW: Source violatedMW value.
        fromStation: Source fromStation value.
        toStation: Source toStation value.
        fromStationkV: Source fromStationkV value.
        toStationkV: Source toStationkV value.
        CCTStatus: Source CCTStatus value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    SCEDTimestamp: datetime
    repeatedHourFlag: StrictBool
    constraintID: StrictInt
    constraintName: StrictStr
    contingencyName: StrictStr
    shadowPrice: Decimal
    maxShadowPrice: Decimal
    limit: Decimal
    value: Decimal
    violatedMW: Decimal
    fromStation: StrictStr
    toStation: StrictStr
    fromStationkV: Decimal
    toStationkV: Decimal
    CCTStatus: StrictStr


NP6_86_CD_SHDW_PRICES_BND_TRNS_CONST_FIELDS = {
    "SCEDTimestamp": "DATETIME",
    "repeatedHourFlag": "BOOLEAN",
    "constraintID": "INTEGER",
    "constraintName": "VARCHAR",
    "contingencyName": "VARCHAR",
    "shadowPrice": "DOUBLE",
    "maxShadowPrice": "DOUBLE",
    "limit": "DOUBLE",
    "value": "DOUBLE",
    "violatedMW": "DOUBLE",
    "fromStation": "VARCHAR",
    "toStation": "VARCHAR",
    "fromStationkV": "DOUBLE",
    "toStationkV": "DOUBLE",
    "CCTStatus": "VARCHAR",
}


class Np6915CdSumHdlLdl(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        SCEDTimestamp: Source SCEDTimestamp value.
        repeatHourFlag: Source repeatHourFlag value.
        GTBD: Source GTBD value.
        sumHDL: Source sumHDL value.
        sumLDL: Source sumLDL value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    SCEDTimestamp: datetime
    repeatHourFlag: StrictBool
    GTBD: Decimal
    sumHDL: Decimal
    sumLDL: Decimal


NP6_915_CD_SUM_HDL_LDL_FIELDS = {
    "SCEDTimestamp": "DATETIME",
    "repeatHourFlag": "BOOLEAN",
    "GTBD": "DOUBLE",
    "sumHDL": "DOUBLE",
    "sumLDL": "DOUBLE",
}


class Np6970CdRtdLmpNodeZoneHub(BaseModel):
    """A row from the observed public field contract.

    Attributes:
        RTDTimestamp: Source RTDTimestamp value.
        repeatHourFlag: Source repeatHourFlag value.
        intervalId: Source intervalId value.
        intervalEnding: Source intervalEnding value.
        intervalRepeatHourFlag: Source intervalRepeatHourFlag value.
        settlementPoint: Source hub, zone, or resource-node identifier.
        settlementPointType: Source settlementPointType value.
        LMP: Source LMP value.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    RTDTimestamp: datetime
    repeatHourFlag: StrictBool
    intervalId: StrictInt
    intervalEnding: datetime
    intervalRepeatHourFlag: StrictBool
    settlementPoint: StrictStr
    settlementPointType: StrictStr
    LMP: Decimal


NP6_970_CD_RTD_LMP_NODE_ZONE_HUB_FIELDS = {
    "RTDTimestamp": "DATETIME",
    "repeatHourFlag": "BOOLEAN",
    "intervalId": "INTEGER",
    "intervalEnding": "DATETIME",
    "intervalRepeatHourFlag": "BOOLEAN",
    "settlementPoint": "VARCHAR",
    "settlementPointType": "VARCHAR",
    "LMP": "DOUBLE",
}
