# Generated by tools/generate_public.py from pinned public field metadata.
"""Observed non-null public rows; unknown schemas fail decoding."""

from datetime import date
from decimal import Decimal

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr


class DamPrice(BaseModel):
    """A non-null row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        settlementPoint: Source hub, zone, or resource-node identifier.
        settlementPointPrice: Decimal source price in dollars per MWh.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictStr
    settlementPoint: StrictStr
    settlementPointPrice: Decimal
    DSTFlag: StrictBool


DAM_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "settlementPoint": "VARCHAR",
    "settlementPointPrice": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}


class DamCapacityPrice(BaseModel):
    """A non-null row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        ancillaryType: Source ancillary-service identifier.
        MCPC: Decimal source capacity clearing price.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictStr
    ancillaryType: StrictStr
    MCPC: Decimal
    DSTFlag: StrictBool


CAPACITY_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "ancillaryType": "VARCHAR",
    "MCPC": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}


class RealTimePrice(BaseModel):
    """A non-null row from the observed public field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        deliveryHour: Source deliveryHour value.
        deliveryInterval: Source deliveryInterval value.
        settlementPoint: Source hub, zone, or resource-node identifier.
        settlementPointType: Source settlementPointType value.
        settlementPointPrice: Decimal source price in dollars per MWh.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    deliveryHour: StrictInt
    deliveryInterval: StrictInt
    settlementPoint: StrictStr
    settlementPointType: StrictStr
    settlementPointPrice: Decimal
    DSTFlag: StrictBool


RT_FIELDS = {
    "deliveryDate": "DATE",
    "deliveryHour": "INTEGER",
    "deliveryInterval": "INTEGER",
    "settlementPoint": "VARCHAR",
    "settlementPointType": "VARCHAR",
    "settlementPointPrice": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}


class SystemLoad(BaseModel):
    """A non-null row from the observed public field contract.

    Attributes:
        operatingDay: Source operatingDay value.
        hourEnding: Source hour-ending label, including 24:00.
        coast: Source coast value.
        east: Source east value.
        farWest: Source farWest value.
        north: Source north value.
        northC: Source northC value.
        southern: Source southern value.
        southC: Source southC value.
        west: Source west value.
        total: Source total value.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    operatingDay: date
    hourEnding: StrictStr
    coast: Decimal
    east: Decimal
    farWest: Decimal
    north: Decimal
    northC: Decimal
    southern: Decimal
    southC: Decimal
    west: Decimal
    total: Decimal
    DSTFlag: StrictBool


LOAD_FIELDS = {
    "operatingDay": "DATE",
    "hourEnding": "VARCHAR",
    "coast": "DOUBLE",
    "east": "DOUBLE",
    "farWest": "DOUBLE",
    "north": "DOUBLE",
    "northC": "DOUBLE",
    "southern": "DOUBLE",
    "southC": "DOUBLE",
    "west": "DOUBLE",
    "total": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}
