# Generated by tools/generate_public.py from pinned public field metadata.
"""Observed non-null DAM rows; unknown schemas fail decoding."""

from datetime import date
from decimal import Decimal

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr


class DamPrice(BaseModel):
    """A non-null row from the observed public DAM field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        settlementPoint: Source hub, zone, or resource-node identifier.
        settlementPointPrice: Decimal source price in dollars per MWh.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictStr
    settlementPoint: StrictStr
    settlementPointPrice: Decimal
    DSTFlag: StrictBool


DAM_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "settlementPoint": "VARCHAR",
    "settlementPointPrice": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}


class DamCapacityPrice(BaseModel):
    """A non-null row from the observed public DAM field contract.

    Attributes:
        deliveryDate: Source operating date, without an inferred timezone.
        hourEnding: Source hour-ending label, including 24:00.
        ancillaryType: Source ancillary-service identifier.
        MCPC: Decimal source capacity clearing price.
        DSTFlag: Raw source flag; no repeated-hour meaning is inferred.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    deliveryDate: date
    hourEnding: StrictStr
    ancillaryType: StrictStr
    MCPC: Decimal
    DSTFlag: StrictBool


CAPACITY_FIELDS = {
    "deliveryDate": "DATE",
    "hourEnding": "VARCHAR",
    "ancillaryType": "VARCHAR",
    "MCPC": "DOUBLE",
    "DSTFlag": "BOOLEAN",
}
