# Generated by tools/generate_public.py; do not edit.
"""Verified public operation identities and complete query filter types."""

from datetime import date
from decimal import Decimal
from typing import TypedDict

from ._generated import (
    DamCapacityPrice,
    DamPrice,
    RealTimePrice,
    SystemLoad,
)
from .schema import Endpoint


class DamPriceFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    settlementPoint: str
    settlementPointPriceFrom: float | Decimal
    settlementPointPriceTo: float | Decimal
    DSTFlag: bool


DAM_PRICES: Endpoint[DamPrice, DamPriceFilters] = Endpoint(
    "/np4-190-cd/dam_stlmnt_pnt_prices", DamPrice, "dam-prices.json"
)


class DamCapacityPriceFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    ancillaryType: str
    MCPCFrom: float | Decimal
    MCPCTo: float | Decimal
    DSTFlag: bool


DAM_CAPACITY_PRICES: Endpoint[DamCapacityPrice, DamCapacityPriceFilters] = Endpoint(
    "/np4-188-cd/dam_clear_price_for_cap", DamCapacityPrice, "dam-capacity.json"
)


class RealTimePriceFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    deliveryHourFrom: int
    deliveryHourTo: int
    deliveryIntervalFrom: int
    deliveryIntervalTo: int
    settlementPoint: str
    settlementPointType: str
    settlementPointPriceFrom: float | Decimal
    settlementPointPriceTo: float | Decimal
    DSTFlag: bool


RT_PRICES: Endpoint[RealTimePrice, RealTimePriceFilters] = Endpoint(
    "/np6-905-cd/spp_node_zone_hub", RealTimePrice, "rt-prices.json"
)


class SystemLoadFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    operatingDayFrom: date
    operatingDayTo: date
    hourEnding: str
    coastFrom: float | Decimal
    coastTo: float | Decimal
    eastFrom: float | Decimal
    eastTo: float | Decimal
    farWestFrom: float | Decimal
    farWestTo: float | Decimal
    northFrom: float | Decimal
    northTo: float | Decimal
    northCFrom: float | Decimal
    northCTo: float | Decimal
    southernFrom: float | Decimal
    southernTo: float | Decimal
    southCFrom: float | Decimal
    southCTo: float | Decimal
    westFrom: float | Decimal
    westTo: float | Decimal
    totalFrom: float | Decimal
    totalTo: float | Decimal
    DSTFlag: bool


SYSTEM_LOAD: Endpoint[SystemLoad, SystemLoadFilters] = Endpoint(
    "/np6-345-cd/act_sys_load_by_wzn", SystemLoad, "system-load.json"
)


ENDPOINTS = (
    DAM_PRICES,
    DAM_CAPACITY_PRICES,
    RT_PRICES,
    SYSTEM_LOAD,
)
