# Generated by tools/generate_public.py; do not edit.
"""Verified public operation identities and complete query filter types."""

from datetime import date, datetime
from decimal import Decimal
from typing import TypedDict

from ._generated import (
    DamCapacityPrice,
    DamPrice,
    Gen55CdHrlyRtLoadFcastActual,
    Np419CdDamAggAsOfferCurve,
    Np433CdDamAsPlan,
    Np686CdShdwPricesBndTrnsConst,
    Np1302AsObligation,
    Np3161Cd7dPlusAvailResPocMargin,
    Np3162Cd7dAvailResPocMargin,
    Np3233CdHourlyResOutageCap,
    Np3560Cd7dLoadFcastByFzn,
    Np3561Cd7dLoadFcastByWzn,
    Np3562CdIhLoadFcastByWzn,
    Np3565CdLfByModelWeatherZone,
    Np4158SgDamEssps,
    Np4159CdLoadDistributionFactors,
    Np4183CdDamHourlyLmp,
    Np4191CdDamShadowPrices,
    Np4192CdDamTotalEnergyPurchased,
    Np4193CdTotalDamEnergySold,
    Np4194CdDamPtpObligationSpResults,
    Np4196MDamPriceCorrectionsEblmp,
    Np4196MDamPriceCorrectionsMcpc,
    Np4196MDamPriceCorrectionsSpp,
    Np4197MRtmPriceCorrectionsEblmp,
    Np4197MRtmPriceCorrectionsMcpcSced,
    Np4197MRtmPriceCorrectionsMcpcSpp,
    Np4197MRtmPriceCorrectionsShadow,
    Np4197MRtmPriceCorrectionsSoglmp,
    Np4197MRtmPriceCorrectionsSogprice,
    Np4197MRtmPriceCorrectionsSplmp,
    Np4197MRtmPriceCorrectionsSpp,
    Np4200CdDamDeEnergizedSpbc,
    Np4212CdDamScedAsDemandCurves,
    Np4213CdHrucAsDemandCurves,
    Np4214CdDrucAsDemandCurves,
    Np4215CdWrucAsDemandCurves,
    Np4231CdElectricalBusMapHeurPrice,
    Np4523CdDamSystemLambda,
    Np6322CdScedSystemLambda,
    Np6323CdRtPriceAdderSced,
    Np6324CdRt15minPriceAdders,
    Np6325CdRtdPriceAdders,
    Np6326CdRtPriceSog,
    Np6327CdLmpSogPriceAdders,
    Np6328CdTotAsResCap,
    Np6329CdRtdIndMcpc,
    Np6331CdRtClearPriceCap,
    Np6332CdRtClearPriceCapSced,
    Np6346CdActSysLoadByFzn,
    Np6787CdLmpElectricalBus,
    Np6788CdLmpNodeZoneHub,
    Np6915CdSumHdlLdl,
    Np6970CdRtdLmpNodeZoneHub,
    RealTimePrice,
    SystemLoad,
)
from .schema import Endpoint


class DamPriceFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    settlementPoint: str
    settlementPointPriceFrom: float | Decimal
    settlementPointPriceTo: float | Decimal
    DSTFlag: bool


DAM_PRICES: Endpoint[DamPrice, DamPriceFilters] = Endpoint(
    "/np4-190-cd/dam_stlmnt_pnt_prices", DamPrice, "dam-prices.json"
)


class DamCapacityPriceFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    ancillaryType: str
    MCPCFrom: float | Decimal
    MCPCTo: float | Decimal
    DSTFlag: bool


DAM_CAPACITY_PRICES: Endpoint[DamCapacityPrice, DamCapacityPriceFilters] = Endpoint(
    "/np4-188-cd/dam_clear_price_for_cap", DamCapacityPrice, "dam-capacity.json"
)


class RealTimePriceFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    deliveryHourFrom: int
    deliveryHourTo: int
    deliveryIntervalFrom: int
    deliveryIntervalTo: int
    settlementPoint: str
    settlementPointType: str
    settlementPointPriceFrom: float | Decimal
    settlementPointPriceTo: float | Decimal
    DSTFlag: bool


RT_PRICES: Endpoint[RealTimePrice, RealTimePriceFilters] = Endpoint(
    "/np6-905-cd/spp_node_zone_hub", RealTimePrice, "rt-prices.json"
)


class SystemLoadFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    operatingDayFrom: date
    operatingDayTo: date
    hourEnding: str
    coastFrom: float | Decimal
    coastTo: float | Decimal
    eastFrom: float | Decimal
    eastTo: float | Decimal
    farWestFrom: float | Decimal
    farWestTo: float | Decimal
    northFrom: float | Decimal
    northTo: float | Decimal
    northCFrom: float | Decimal
    northCTo: float | Decimal
    southernFrom: float | Decimal
    southernTo: float | Decimal
    southCFrom: float | Decimal
    southCTo: float | Decimal
    westFrom: float | Decimal
    westTo: float | Decimal
    totalFrom: float | Decimal
    totalTo: float | Decimal
    DSTFlag: bool


SYSTEM_LOAD: Endpoint[SystemLoad, SystemLoadFilters] = Endpoint(
    "/np6-345-cd/act_sys_load_by_wzn", SystemLoad, "system-load.json"
)


class Gen55CdHrlyRtLoadFcastActualFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    hourEndingFrom: int
    hourEndingTo: int
    currentDayFcastFrom: float | Decimal
    currentDayFcastTo: float | Decimal
    dayAheadFcastFrom: float | Decimal
    dayAheadFcastTo: float | Decimal
    actualLoadFrom: float | Decimal
    actualLoadTo: float | Decimal
    dayAheadHSLFrom: float | Decimal
    dayAheadHSLTo: float | Decimal
    currentDayHSLFrom: float | Decimal
    currentDayHSLTo: float | Decimal
    DSTFlag: bool


GEN_55_CD_HRLY_RT_LOAD_FCAST_ACTUAL: Endpoint[
    Gen55CdHrlyRtLoadFcastActual, Gen55CdHrlyRtLoadFcastActualFilters
] = Endpoint(
    "/gen-55-cd/hrly_rt_load_fcast_actual",
    Gen55CdHrlyRtLoadFcastActual,
    "gen-55-cd--hrly_rt_load_fcast_actual.json",
)


class Np1302AsObligationFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    qseName: str
    REGUPOblAdvisoryFrom: float | Decimal
    REGUPOblAdvisoryTo: float | Decimal
    REGDNOblAdvisoryFrom: float | Decimal
    REGDNOblAdvisoryTo: float | Decimal
    RRSOblAdvisoryFrom: float | Decimal
    RRSOblAdvisoryTo: float | Decimal
    NSPINOblAdvisoryFrom: float | Decimal
    NSPINOblAdvisoryTo: float | Decimal
    ECRSOblAdvisoryFrom: float | Decimal
    ECRSOblAdvisoryTo: float | Decimal
    REGUPOblFinalFrom: float | Decimal
    REGUPOblFinalTo: float | Decimal
    REGDNOblFinalFrom: float | Decimal
    REGDNOblFinalTo: float | Decimal
    RRSOblFinalFrom: float | Decimal
    RRSOblFinalTo: float | Decimal
    NSPINOblFinalFrom: float | Decimal
    NSPINOblFinalTo: float | Decimal
    ECRSOblFinalFrom: float | Decimal
    ECRSOblFinalTo: float | Decimal


NP1_302_AS_OBLIGATION: Endpoint[Np1302AsObligation, Np1302AsObligationFilters] = (
    Endpoint(
        "/np1-302/as_obligation", Np1302AsObligation, "np1-302--as_obligation.json"
    )
)


class Np3161Cd7dPlusAvailResPocMarginFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    postedDatetimeFrom: datetime
    postedDatetimeTo: datetime
    operatingDateFrom: date
    operatingDateTo: date
    nonIRRNonPUNFrom: float | Decimal
    nonIRRNonPUNTo: float | Decimal
    ESRFrom: float | Decimal
    ESRTo: float | Decimal
    aggApprvdNonIRRNonPUNFrom: float | Decimal
    aggApprvdNonIRRNonPUNTo: float | Decimal
    aggRcvdNonIRRNonPUNFrom: float | Decimal
    aggRcvdNonIRRNonPUNTo: float | Decimal
    IRRFrom: float | Decimal
    IRRTo: float | Decimal
    aggApprvdIRRFrom: float | Decimal
    aggApprvdIRRTo: float | Decimal
    aggRcvdIRRFrom: float | Decimal
    aggRcvdIRRTo: float | Decimal
    aggApprvdESRFrom: float | Decimal
    aggApprvdESRTo: float | Decimal
    aggRcvdESRFrom: float | Decimal
    aggRcvdESRTo: float | Decimal


NP3_161_CD_7D_PLUS_AVAIL_RES_POC_MARGIN: Endpoint[
    Np3161Cd7dPlusAvailResPocMargin, Np3161Cd7dPlusAvailResPocMarginFilters
] = Endpoint(
    "/np3-161-cd/7d_plus_avail_res_poc_margin",
    Np3161Cd7dPlusAvailResPocMargin,
    "np3-161-cd--7d_plus_avail_res_poc_margin.json",
)


class Np3162Cd7dAvailResPocMarginFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    aggRcvdESRFrom: float | Decimal
    aggRcvdESRTo: float | Decimal
    repeatedHourFlag: bool
    postedDatetimeFrom: datetime
    postedDatetimeTo: datetime
    operatingDateFrom: date
    operatingDateTo: date
    hourEndingFrom: int
    hourEndingTo: int
    nonIrrNonPunFrom: float | Decimal
    nonIrrNonPunTo: float | Decimal
    aggApprvdNonIRRNonPUNFrom: float | Decimal
    aggApprvdNonIRRNonPUNTo: float | Decimal
    aggRcvdNonIRRNonPUNFrom: float | Decimal
    aggRcvdNonIRRNonPUNTo: float | Decimal
    IRRFrom: float | Decimal
    IRRTo: float | Decimal
    aggApprvdIRRFrom: float | Decimal
    aggApprvdIRRTo: float | Decimal
    aggRcvdIRRFrom: float | Decimal
    aggRcvdIRRTo: float | Decimal
    ESRFrom: float | Decimal
    ESRTo: float | Decimal
    aggApprvdESRFrom: float | Decimal
    aggApprvdESRTo: float | Decimal


NP3_162_CD_7D_AVAIL_RES_POC_MARGIN: Endpoint[
    Np3162Cd7dAvailResPocMargin, Np3162Cd7dAvailResPocMarginFilters
] = Endpoint(
    "/np3-162-cd/7d_avail_res_poc_margin",
    Np3162Cd7dAvailResPocMargin,
    "np3-162-cd--7d_avail_res_poc_margin.json",
)


class Np3233CdHourlyResOutageCapFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    operatingDateFrom: date
    operatingDateTo: date
    hourEndingFrom: int
    hourEndingTo: int
    totalResourceMWZoneSouthFrom: int
    totalResourceMWZoneSouthTo: int
    totalResourceMWZoneNorthFrom: int
    totalResourceMWZoneNorthTo: int
    totalResourceMWZoneWestFrom: int
    totalResourceMWZoneWestTo: int
    totalResourceMWZoneHoustonFrom: int
    totalResourceMWZoneHoustonTo: int
    totalIRRMWZoneSouthFrom: int
    totalIRRMWZoneSouthTo: int
    totalIRRMWZoneNorthFrom: int
    totalIRRMWZoneNorthTo: int
    totalIRRMWZoneWestFrom: int
    totalIRRMWZoneWestTo: int
    totalIRRMWZoneHoustonFrom: int
    totalIRRMWZoneHoustonTo: int
    totalNewEquipResourceMWZoneSouthFrom: int
    totalNewEquipResourceMWZoneSouthTo: int
    totalNewEquipResourceMWZoneNorthFrom: int
    totalNewEquipResourceMWZoneNorthTo: int
    totalNewEquipResourceMWZoneWestFrom: int
    totalNewEquipResourceMWZoneWestTo: int
    totalNewEquipResourceMWZoneHoustonFrom: int
    totalNewEquipResourceMWZoneHoustonTo: int
    postedDatetimeFrom: datetime
    postedDatetimeTo: datetime


NP3_233_CD_HOURLY_RES_OUTAGE_CAP: Endpoint[
    Np3233CdHourlyResOutageCap, Np3233CdHourlyResOutageCapFilters
] = Endpoint(
    "/np3-233-cd/hourly_res_outage_cap",
    Np3233CdHourlyResOutageCap,
    "np3-233-cd--hourly_res_outage_cap.json",
)


class Np3560Cd7dLoadFcastByFznFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    postedDatetimeFrom: datetime
    postedDatetimeTo: datetime
    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    northFrom: float | Decimal
    northTo: float | Decimal
    southFrom: float | Decimal
    southTo: float | Decimal
    westFrom: float | Decimal
    westTo: float | Decimal
    houstonFrom: float | Decimal
    houstonTo: float | Decimal
    systemTotalFrom: float | Decimal
    systemTotalTo: float | Decimal
    DSTFlag: bool


NP3_560_CD_7D_LOAD_FCAST_BY_FZN: Endpoint[
    Np3560Cd7dLoadFcastByFzn, Np3560Cd7dLoadFcastByFznFilters
] = Endpoint(
    "/np3-560-cd/7d_load_fcast_by_fzn",
    Np3560Cd7dLoadFcastByFzn,
    "np3-560-cd--7d_load_fcast_by_fzn.json",
)


class Np3561Cd7dLoadFcastByWznFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    postedDatetimeFrom: datetime
    postedDatetimeTo: datetime
    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    coastFrom: float | Decimal
    coastTo: float | Decimal
    eastFrom: float | Decimal
    eastTo: float | Decimal
    farWestFrom: float | Decimal
    farWestTo: float | Decimal
    northFrom: float | Decimal
    northTo: float | Decimal
    northCentralFrom: float | Decimal
    northCentralTo: float | Decimal
    southCentralFrom: float | Decimal
    southCentralTo: float | Decimal
    southernFrom: float | Decimal
    southernTo: float | Decimal
    westFrom: float | Decimal
    westTo: float | Decimal
    systemTotalFrom: float | Decimal
    systemTotalTo: float | Decimal
    DSTFlag: bool


NP3_561_CD_7D_LOAD_FCAST_BY_WZN: Endpoint[
    Np3561Cd7dLoadFcastByWzn, Np3561Cd7dLoadFcastByWznFilters
] = Endpoint(
    "/np3-561-cd/7d_load_fcast_by_wzn",
    Np3561Cd7dLoadFcastByWzn,
    "np3-561-cd--7d_load_fcast_by_wzn.json",
)


class Np3562CdIhLoadFcastByWznFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    farWestFrom: float | Decimal
    farWestTo: float | Decimal
    northFrom: float | Decimal
    northTo: float | Decimal
    northCentralFrom: float | Decimal
    northCentralTo: float | Decimal
    southCentralFrom: float | Decimal
    southCentralTo: float | Decimal
    southernFrom: float | Decimal
    southernTo: float | Decimal
    westFrom: float | Decimal
    westTo: float | Decimal
    systemTotalFrom: float | Decimal
    systemTotalTo: float | Decimal
    model: str
    inUseFlag: bool
    DSTFlag: bool
    postedDatetimeFrom: datetime
    postedDatetimeTo: datetime
    intervalEndingFrom: datetime
    intervalEndingTo: datetime
    coastFrom: float | Decimal
    coastTo: float | Decimal
    eastFrom: float | Decimal
    eastTo: float | Decimal


NP3_562_CD_IH_LOAD_FCAST_BY_WZN: Endpoint[
    Np3562CdIhLoadFcastByWzn, Np3562CdIhLoadFcastByWznFilters
] = Endpoint(
    "/np3-562-cd/ih_load_fcast_by_wzn",
    Np3562CdIhLoadFcastByWzn,
    "np3-562-cd--ih_load_fcast_by_wzn.json",
)


class Np3565CdLfByModelWeatherZoneFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    DSTFlag: bool
    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    coastFrom: float | Decimal
    coastTo: float | Decimal
    eastFrom: float | Decimal
    eastTo: float | Decimal
    farWestFrom: float | Decimal
    farWestTo: float | Decimal
    northFrom: float | Decimal
    northTo: float | Decimal
    northCentralFrom: float | Decimal
    northCentralTo: float | Decimal
    southCentralFrom: float | Decimal
    southCentralTo: float | Decimal
    southernFrom: float | Decimal
    southernTo: float | Decimal
    westFrom: float | Decimal
    westTo: float | Decimal
    postedDatetimeFrom: datetime
    postedDatetimeTo: datetime
    systemTotalFrom: float | Decimal
    systemTotalTo: float | Decimal
    model: str
    inUseFlag: bool


NP3_565_CD_LF_BY_MODEL_WEATHER_ZONE: Endpoint[
    Np3565CdLfByModelWeatherZone, Np3565CdLfByModelWeatherZoneFilters
] = Endpoint(
    "/np3-565-cd/lf_by_model_weather_zone",
    Np3565CdLfByModelWeatherZone,
    "np3-565-cd--lf_by_model_weather_zone.json",
)


class Np4158SgDamEsspsFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    postedDatetimeFrom: datetime
    postedDatetimeTo: datetime
    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    settlementPoint: str
    groupIndexFrom: int
    groupIndexTo: int
    updateTimeFrom: datetime
    updateTimeTo: datetime
    repeatHourFlag: bool


NP4_158_SG_DAM_ESSPS: Endpoint[Np4158SgDamEssps, Np4158SgDamEsspsFilters] = Endpoint(
    "/np4-158-sg/dam_essps", Np4158SgDamEssps, "np4-158-sg--dam_essps.json"
)


class Np4159CdLoadDistributionFactorsFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    LDFDateFrom: date
    LDFDateTo: date
    LDFHour: str
    substation: str
    distributionFactorFrom: float | Decimal
    distributionFactorTo: float | Decimal
    loadId: str
    MVARDistributionFactorFrom: float | Decimal
    MVARDistributionFactorTo: float | Decimal
    postedDatetimeFrom: datetime
    postedDatetimeTo: datetime
    MRIDLoad: str
    DSTFlag: bool


NP4_159_CD_LOAD_DISTRIBUTION_FACTORS: Endpoint[
    Np4159CdLoadDistributionFactors, Np4159CdLoadDistributionFactorsFilters
] = Endpoint(
    "/np4-159-cd/load_distribution_factors",
    Np4159CdLoadDistributionFactors,
    "np4-159-cd--load_distribution_factors.json",
)


class Np4183CdDamHourlyLmpFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    DSTFlag: bool
    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    busName: str
    LMPFrom: float | Decimal
    LMPTo: float | Decimal


NP4_183_CD_DAM_HOURLY_LMP: Endpoint[
    Np4183CdDamHourlyLmp, Np4183CdDamHourlyLmpFilters
] = Endpoint(
    "/np4-183-cd/dam_hourly_lmp",
    Np4183CdDamHourlyLmp,
    "np4-183-cd--dam_hourly_lmp.json",
)


class Np419CdDamAggAsOfferCurveFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    ancillaryType: str
    priceFrom: float | Decimal
    priceTo: float | Decimal
    quantityFrom: float | Decimal
    quantityTo: float | Decimal
    DSTFlag: bool


NP4_19_CD_DAM_AGG_AS_OFFER_CURVE: Endpoint[
    Np419CdDamAggAsOfferCurve, Np419CdDamAggAsOfferCurveFilters
] = Endpoint(
    "/np4-19-cd/dam_agg_as_offer_curve",
    Np419CdDamAggAsOfferCurve,
    "np4-19-cd--dam_agg_as_offer_curve.json",
)


class Np4191CdDamShadowPricesFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    constraintIdFrom: int
    constraintIdTo: int
    constraintName: str
    contingencyName: str
    constraintLimitFrom: int
    constraintLimitTo: int
    constraintValueFrom: int
    constraintValueTo: int
    violationAmountFrom: int
    violationAmountTo: int
    shadowPriceFrom: float | Decimal
    shadowPriceTo: float | Decimal
    fromStation: str
    toStation: str
    fromStationkVFrom: float | Decimal
    fromStationkVTo: float | Decimal
    toStationkVFrom: float | Decimal
    toStationkVTo: float | Decimal
    deliveryTimeFrom: datetime
    deliveryTimeTo: datetime
    DSTFlag: bool


NP4_191_CD_DAM_SHADOW_PRICES: Endpoint[
    Np4191CdDamShadowPrices, Np4191CdDamShadowPricesFilters
] = Endpoint(
    "/np4-191-cd/dam_shadow_prices",
    Np4191CdDamShadowPrices,
    "np4-191-cd--dam_shadow_prices.json",
)


class Np4192CdDamTotalEnergyPurchasedFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    hourEnding: str
    settlementPoint: str
    totalDamEnergyBoughtFrom: float | Decimal
    totalDamEnergyBoughtTo: float | Decimal
    repeatHourFlag: bool
    deliveryDateFrom: date
    deliveryDateTo: date


NP4_192_CD_DAM_TOTAL_ENERGY_PURCHASED: Endpoint[
    Np4192CdDamTotalEnergyPurchased, Np4192CdDamTotalEnergyPurchasedFilters
] = Endpoint(
    "/np4-192-cd/dam_total_energy_purchased",
    Np4192CdDamTotalEnergyPurchased,
    "np4-192-cd--dam_total_energy_purchased.json",
)


class Np4193CdTotalDamEnergySoldFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    settlementPoint: str
    totalDAMEnergySoldFrom: float | Decimal
    totalDAMEnergySoldTo: float | Decimal
    repeatHourFlag: bool


NP4_193_CD_TOTAL_DAM_ENERGY_SOLD: Endpoint[
    Np4193CdTotalDamEnergySold, Np4193CdTotalDamEnergySoldFilters
] = Endpoint(
    "/np4-193-cd/total_dam_energy_sold",
    Np4193CdTotalDamEnergySold,
    "np4-193-cd--total_dam_energy_sold.json",
)


class Np4194CdDamPtpObligationSpResultsFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    stlPnt: str
    totalPtpOblAwardedSourceFrom: float | Decimal
    totalPtpOblAwardedSourceTo: float | Decimal
    totalPtpOblAwardedSinkFrom: float | Decimal
    totalPtpOblAwardedSinkTo: float | Decimal
    repeatedHourFlag: bool


NP4_194_CD_DAM_PTP_OBLIGATION_SP_RESULTS: Endpoint[
    Np4194CdDamPtpObligationSpResults, Np4194CdDamPtpObligationSpResultsFilters
] = Endpoint(
    "/np4-194-cd/dam_ptp_obligation_sp_results",
    Np4194CdDamPtpObligationSpResults,
    "np4-194-cd--dam_ptp_obligation_sp_results.json",
)


class Np4196MDamPriceCorrectionsEblmpFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    deliveryHourFrom: int
    deliveryHourTo: int
    electricalBus: str
    LMPOriginalFrom: float | Decimal
    LMPOriginalTo: float | Decimal
    LMPCorrectedFrom: float | Decimal
    LMPCorrectedTo: float | Decimal
    priceCorrectionTimeFrom: datetime
    priceCorrectionTimeTo: datetime
    DSTFlag: bool


NP4_196_M_DAM_PRICE_CORRECTIONS_EBLMP: Endpoint[
    Np4196MDamPriceCorrectionsEblmp, Np4196MDamPriceCorrectionsEblmpFilters
] = Endpoint(
    "/np4-196-m/dam_price_corrections_eblmp",
    Np4196MDamPriceCorrectionsEblmp,
    "np4-196-m--dam_price_corrections_eblmp.json",
)


class Np4196MDamPriceCorrectionsMcpcFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    deliveryHourFrom: int
    deliveryHourTo: int
    ASType: str
    MCPCOriginalFrom: float | Decimal
    MCPCOriginalTo: float | Decimal
    MCPCCorrectedFrom: float | Decimal
    MCPCCorrectedTo: float | Decimal
    priceCorrectionTimeFrom: datetime
    priceCorrectionTimeTo: datetime
    DSTFlag: bool


NP4_196_M_DAM_PRICE_CORRECTIONS_MCPC: Endpoint[
    Np4196MDamPriceCorrectionsMcpc, Np4196MDamPriceCorrectionsMcpcFilters
] = Endpoint(
    "/np4-196-m/dam_price_corrections_mcpc",
    Np4196MDamPriceCorrectionsMcpc,
    "np4-196-m--dam_price_corrections_mcpc.json",
)


class Np4196MDamPriceCorrectionsSppFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    priceCorrectionTimeFrom: datetime
    priceCorrectionTimeTo: datetime
    DSTFlag: bool
    deliveryDateFrom: date
    deliveryDateTo: date
    deliveryHourFrom: int
    deliveryHourTo: int
    settlementPoint: str
    SPPOriginalFrom: float | Decimal
    SPPOriginalTo: float | Decimal
    SPPCorrectedFrom: float | Decimal
    SPPCorrectedTo: float | Decimal


NP4_196_M_DAM_PRICE_CORRECTIONS_SPP: Endpoint[
    Np4196MDamPriceCorrectionsSpp, Np4196MDamPriceCorrectionsSppFilters
] = Endpoint(
    "/np4-196-m/dam_price_corrections_spp",
    Np4196MDamPriceCorrectionsSpp,
    "np4-196-m--dam_price_corrections_spp.json",
)


class Np4197MRtmPriceCorrectionsEblmpFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    cappedLMPOriginalFrom: float | Decimal
    cappedLMPOriginalTo: float | Decimal
    uncappedLMPOriginalFrom: float | Decimal
    uncappedLMPOriginalTo: float | Decimal
    cappedLMPCorrectedFrom: float | Decimal
    cappedLMPCorrectedTo: float | Decimal
    uncappedLMPCorrectedFrom: float | Decimal
    uncappedLMPCorrectedTo: float | Decimal
    priceCorrectionTimeFrom: datetime
    priceCorrectionTimeTo: datetime
    repeatedHourFlag: bool
    SCEDTimestampFrom: datetime
    SCEDTimestampTo: datetime
    electricalBus: str


NP4_197_M_RTM_PRICE_CORRECTIONS_EBLMP: Endpoint[
    Np4197MRtmPriceCorrectionsEblmp, Np4197MRtmPriceCorrectionsEblmpFilters
] = Endpoint(
    "/np4-197-m/rtm_price_corrections_eblmp",
    Np4197MRtmPriceCorrectionsEblmp,
    "np4-197-m--rtm_price_corrections_eblmp.json",
)


class Np4197MRtmPriceCorrectionsMcpcScedFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    SCEDTimestampFrom: datetime
    SCEDTimestampTo: datetime
    ASType: str
    cappedMCPCOriginalFrom: float | Decimal
    cappedMCPCOriginalTo: float | Decimal
    uncappedMCPCOriginalFrom: float | Decimal
    uncappedMCPCOriginalTo: float | Decimal
    cappedMCPCCorrectedFrom: float | Decimal
    cappedMCPCCorrectedTo: float | Decimal
    uncappedMCPCCorrectedFrom: float | Decimal
    uncappedMCPCCorrectedTo: float | Decimal
    priceCorrectionTimeFrom: datetime
    priceCorrectionTimeTo: datetime
    repeatedHourFlag: bool


NP4_197_M_RTM_PRICE_CORRECTIONS_MCPC_SCED: Endpoint[
    Np4197MRtmPriceCorrectionsMcpcSced, Np4197MRtmPriceCorrectionsMcpcScedFilters
] = Endpoint(
    "/np4-197-m/rtm_price_corrections_mcpc_sced",
    Np4197MRtmPriceCorrectionsMcpcSced,
    "np4-197-m--rtm_price_corrections_mcpc_sced.json",
)


class Np4197MRtmPriceCorrectionsMcpcSppFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    ASType: str
    MCPCOriginalFrom: float | Decimal
    MCPCOriginalTo: float | Decimal
    MCPCCorrectedFrom: float | Decimal
    MCPCCorrectedTo: float | Decimal
    priceCorrectionTimeFrom: datetime
    priceCorrectionTimeTo: datetime
    repeatHourFlag: bool
    deliveryDateFrom: date
    deliveryDateTo: date
    deliveryHourFrom: int
    deliveryHourTo: int
    deliveryIntervalFrom: int
    deliveryIntervalTo: int


NP4_197_M_RTM_PRICE_CORRECTIONS_MCPC_SPP: Endpoint[
    Np4197MRtmPriceCorrectionsMcpcSpp, Np4197MRtmPriceCorrectionsMcpcSppFilters
] = Endpoint(
    "/np4-197-m/rtm_price_corrections_mcpc_spp",
    Np4197MRtmPriceCorrectionsMcpcSpp,
    "np4-197-m--rtm_price_corrections_mcpc_spp.json",
)


class Np4197MRtmPriceCorrectionsShadowFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    SCEDTimestampFrom: datetime
    SCEDTimestampTo: datetime
    constraintIdFrom: int
    constraintIdTo: int
    constraintName: str
    contingencyName: str
    shadowPriceOriginalFrom: float | Decimal
    shadowPriceOriginalTo: float | Decimal
    shadowPriceCorrectedFrom: float | Decimal
    shadowPriceCorrectedTo: float | Decimal
    limitOriginalFrom: float | Decimal
    limitOriginalTo: float | Decimal
    limitCorrectedFrom: float | Decimal
    limitCorrectedTo: float | Decimal
    valueOriginalFrom: float | Decimal
    valueOriginalTo: float | Decimal
    valueCorrectedFrom: float | Decimal
    valueCorrectedTo: float | Decimal
    priceCorrectionTimeFrom: datetime
    priceCorrectionTimeTo: datetime
    DSTFlag: bool


NP4_197_M_RTM_PRICE_CORRECTIONS_SHADOW: Endpoint[
    Np4197MRtmPriceCorrectionsShadow, Np4197MRtmPriceCorrectionsShadowFilters
] = Endpoint(
    "/np4-197-m/rtm_price_corrections_shadow",
    Np4197MRtmPriceCorrectionsShadow,
    "np4-197-m--rtm_price_corrections_shadow.json",
)


class Np4197MRtmPriceCorrectionsSoglmpFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    SCEDTimestampFrom: datetime
    SCEDTimestampTo: datetime
    resourceType: str
    resourceName: str
    meterName: str
    meterLMPOriginalFrom: float | Decimal
    meterLMPOriginalTo: float | Decimal
    meterLMPCorrectedFrom: float | Decimal
    meterLMPCorrectedTo: float | Decimal
    RTRDPAOriginalFrom: float | Decimal
    RTRDPAOriginalTo: float | Decimal
    RTRDPACorrectedFrom: float | Decimal
    RTRDPACorrectedTo: float | Decimal
    finalLMPOriginalFrom: float | Decimal
    finalLMPOriginalTo: float | Decimal
    finalLMPCorrectedFrom: float | Decimal
    finalLMPCorrectedTo: float | Decimal
    priceCorrectionTimeFrom: datetime
    priceCorrectionTimeTo: datetime
    repeatHourFlag: bool


NP4_197_M_RTM_PRICE_CORRECTIONS_SOGLMP: Endpoint[
    Np4197MRtmPriceCorrectionsSoglmp, Np4197MRtmPriceCorrectionsSoglmpFilters
] = Endpoint(
    "/np4-197-m/rtm_price_corrections_soglmp",
    Np4197MRtmPriceCorrectionsSoglmp,
    "np4-197-m--rtm_price_corrections_soglmp.json",
)


class Np4197MRtmPriceCorrectionsSogpriceFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    deliveryHourFrom: int
    deliveryHourTo: int
    deliveryIntervalFrom: int
    deliveryIntervalTo: int
    resourceType: str
    resourceName: str
    meterName: str
    priceOriginalFrom: float | Decimal
    priceOriginalTo: float | Decimal
    priceCorrectedFrom: float | Decimal
    priceCorrectedTo: float | Decimal
    priceCorrectionTimeFrom: datetime
    priceCorrectionTimeTo: datetime
    DSTFlag: bool


NP4_197_M_RTM_PRICE_CORRECTIONS_SOGPRICE: Endpoint[
    Np4197MRtmPriceCorrectionsSogprice, Np4197MRtmPriceCorrectionsSogpriceFilters
] = Endpoint(
    "/np4-197-m/rtm_price_corrections_sogprice",
    Np4197MRtmPriceCorrectionsSogprice,
    "np4-197-m--rtm_price_corrections_sogprice.json",
)


class Np4197MRtmPriceCorrectionsSplmpFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    settlementPointName: str
    LMPOriginalFrom: float | Decimal
    LMPOriginalTo: float | Decimal
    LMPCorrectedFrom: float | Decimal
    LMPCorrectedTo: float | Decimal
    priceCorrectionTimeFrom: datetime
    priceCorrectionTimeTo: datetime
    DSTFlag: bool
    SCEDTimestampFrom: datetime
    SCEDTimestampTo: datetime


NP4_197_M_RTM_PRICE_CORRECTIONS_SPLMP: Endpoint[
    Np4197MRtmPriceCorrectionsSplmp, Np4197MRtmPriceCorrectionsSplmpFilters
] = Endpoint(
    "/np4-197-m/rtm_price_corrections_splmp",
    Np4197MRtmPriceCorrectionsSplmp,
    "np4-197-m--rtm_price_corrections_splmp.json",
)


class Np4197MRtmPriceCorrectionsSppFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    deliveryHourFrom: int
    deliveryHourTo: int
    deliveryIntervalFrom: int
    deliveryIntervalTo: int
    settlementPointName: str
    settlementPointType: str
    SPPOriginalFrom: float | Decimal
    SPPOriginalTo: float | Decimal
    SPPCorrectedFrom: float | Decimal
    SPPCorrectedTo: float | Decimal
    priceCorrectionTimeFrom: datetime
    priceCorrectionTimeTo: datetime
    DSTFlag: bool


NP4_197_M_RTM_PRICE_CORRECTIONS_SPP: Endpoint[
    Np4197MRtmPriceCorrectionsSpp, Np4197MRtmPriceCorrectionsSppFilters
] = Endpoint(
    "/np4-197-m/rtm_price_corrections_spp",
    Np4197MRtmPriceCorrectionsSpp,
    "np4-197-m--rtm_price_corrections_spp.json",
)


class Np4200CdDamDeEnergizedSpbcFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    settlementPoint: str
    repeatedHourFlag: bool


NP4_200_CD_DAM_DE_ENERGIZED_SPBC: Endpoint[
    Np4200CdDamDeEnergizedSpbc, Np4200CdDamDeEnergizedSpbcFilters
] = Endpoint(
    "/np4-200-cd/dam_de_energized_spbc",
    Np4200CdDamDeEnergizedSpbc,
    "np4-200-cd--dam_de_energized_spbc.json",
)


class Np4212CdDamScedAsDemandCurvesFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    quantityFrom: float | Decimal
    quantityTo: float | Decimal
    priceFrom: float | Decimal
    priceTo: float | Decimal
    repeatHourFlag: bool
    postedDatetimeFrom: datetime
    postedDatetimeTo: datetime
    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    ASType: str
    demandCurvePointFrom: float | Decimal
    demandCurvePointTo: float | Decimal


NP4_212_CD_DAM_SCED_AS_DEMAND_CURVES: Endpoint[
    Np4212CdDamScedAsDemandCurves, Np4212CdDamScedAsDemandCurvesFilters
] = Endpoint(
    "/np4-212-cd/dam_sced_as_demand_curves",
    Np4212CdDamScedAsDemandCurves,
    "np4-212-cd--dam_sced_as_demand_curves.json",
)


class Np4213CdHrucAsDemandCurvesFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    quantityFrom: float | Decimal
    quantityTo: float | Decimal
    priceFrom: float | Decimal
    priceTo: float | Decimal
    repeatHourFlag: bool
    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    RUCTimestampFrom: datetime
    RUCTimestampTo: datetime
    ASType: str
    demandCurvePointFrom: float | Decimal
    demandCurvePointTo: float | Decimal


NP4_213_CD_HRUC_AS_DEMAND_CURVES: Endpoint[
    Np4213CdHrucAsDemandCurves, Np4213CdHrucAsDemandCurvesFilters
] = Endpoint(
    "/np4-213-cd/hruc_as_demand_curves",
    Np4213CdHrucAsDemandCurves,
    "np4-213-cd--hruc_as_demand_curves.json",
)


class Np4214CdDrucAsDemandCurvesFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    RUCTimestampFrom: datetime
    RUCTimestampTo: datetime
    ASType: str
    demandCurvePointFrom: float | Decimal
    demandCurvePointTo: float | Decimal
    quantityFrom: float | Decimal
    quantityTo: float | Decimal
    priceFrom: float | Decimal
    priceTo: float | Decimal
    repeatHourFlag: bool


NP4_214_CD_DRUC_AS_DEMAND_CURVES: Endpoint[
    Np4214CdDrucAsDemandCurves, Np4214CdDrucAsDemandCurvesFilters
] = Endpoint(
    "/np4-214-cd/druc_as_demand_curves",
    Np4214CdDrucAsDemandCurves,
    "np4-214-cd--druc_as_demand_curves.json",
)


class Np4215CdWrucAsDemandCurvesFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    quantityFrom: float | Decimal
    quantityTo: float | Decimal
    priceFrom: float | Decimal
    priceTo: float | Decimal
    repeatHourFlag: bool
    postedDatetimeFrom: datetime
    postedDatetimeTo: datetime
    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    RUCTimestampFrom: datetime
    RUCTimestampTo: datetime
    ASType: str
    demandCurvePointFrom: float | Decimal
    demandCurvePointTo: float | Decimal


NP4_215_CD_WRUC_AS_DEMAND_CURVES: Endpoint[
    Np4215CdWrucAsDemandCurves, Np4215CdWrucAsDemandCurvesFilters
] = Endpoint(
    "/np4-215-cd/wruc_as_demand_curves",
    Np4215CdWrucAsDemandCurves,
    "np4-215-cd--wruc_as_demand_curves.json",
)


class Np4231CdElectricalBusMapHeurPriceFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    toEBName: str
    type: str
    priorityFrom: float | Decimal
    priorityTo: float | Decimal
    postedDatetimeFrom: datetime
    postedDatetimeTo: datetime
    marketType: str
    fromEBName: str


NP4_231_CD_ELECTRICAL_BUS_MAP_HEUR_PRICE: Endpoint[
    Np4231CdElectricalBusMapHeurPrice, Np4231CdElectricalBusMapHeurPriceFilters
] = Endpoint(
    "/np4-231-cd/electrical_bus_map_heur_price",
    Np4231CdElectricalBusMapHeurPrice,
    "np4-231-cd--electrical_bus_map_heur_price.json",
)


class Np433CdDamAsPlanFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    ancillaryType: str
    quantityFrom: int
    quantityTo: int
    DSTFlag: bool
    postedDatetimeFrom: datetime
    postedDatetimeTo: datetime


NP4_33_CD_DAM_AS_PLAN: Endpoint[Np433CdDamAsPlan, Np433CdDamAsPlanFilters] = Endpoint(
    "/np4-33-cd/dam_as_plan", Np433CdDamAsPlan, "np4-33-cd--dam_as_plan.json"
)


class Np4523CdDamSystemLambdaFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    hourEnding: str
    systemLambdaFrom: float | Decimal
    systemLambdaTo: float | Decimal
    DSTFlag: bool


NP4_523_CD_DAM_SYSTEM_LAMBDA: Endpoint[
    Np4523CdDamSystemLambda, Np4523CdDamSystemLambdaFilters
] = Endpoint(
    "/np4-523-cd/dam_system_lambda",
    Np4523CdDamSystemLambda,
    "np4-523-cd--dam_system_lambda.json",
)


class Np6322CdScedSystemLambdaFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    SCEDTimestampFrom: datetime
    SCEDTimestampTo: datetime
    repeatedHourFlag: bool
    cappedSystemLambdaFrom: float | Decimal
    cappedSystemLambdaTo: float | Decimal
    uncappedSystemLambdaFrom: float | Decimal
    uncappedSystemLambdaTo: float | Decimal


NP6_322_CD_SCED_SYSTEM_LAMBDA: Endpoint[
    Np6322CdScedSystemLambda, Np6322CdScedSystemLambdaFilters
] = Endpoint(
    "/np6-322-cd/sced_system_lambda",
    Np6322CdScedSystemLambda,
    "np6-322-cd--sced_system_lambda.json",
)


class Np6323CdRtPriceAdderScedFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    SCEDTimestampFrom: datetime
    SCEDTimestampTo: datetime
    repeatHourFlag: bool
    systemLambdaFrom: float | Decimal
    systemLambdaTo: float | Decimal
    RTRDPAFrom: float | Decimal
    RTRDPATo: float | Decimal
    RTRDPARUSFrom: float | Decimal
    RTRDPARUSTo: float | Decimal
    RTRDPARDSFrom: float | Decimal
    RTRDPARDSTo: float | Decimal
    RTRDPARRSFrom: float | Decimal
    RTRDPARRSTo: float | Decimal
    RTRDPAECRSFrom: float | Decimal
    RTRDPAECRSTo: float | Decimal
    RTRDPANSSFrom: float | Decimal
    RTRDPANSSTo: float | Decimal
    RTRRUCFrom: float | Decimal
    RTRRUCTo: float | Decimal
    RTRRMRFrom: float | Decimal
    RTRRMRTo: float | Decimal
    RTDNCLRFrom: float | Decimal
    RTDNCLRTo: float | Decimal
    RTDERSFrom: float | Decimal
    RTDERSTo: float | Decimal
    RTDCTIEIMPORTFrom: float | Decimal
    RTDCTIEIMPORTTo: float | Decimal
    RTDCTIEEXPORTFrom: float | Decimal
    RTDCTIEEXPORTTo: float | Decimal
    RTBLTIMPORTFrom: float | Decimal
    RTBLTIMPORTTo: float | Decimal
    RTBLTEXPORTFrom: float | Decimal
    RTBLTEXPORTTo: float | Decimal
    RTOLLSLFrom: float | Decimal
    RTOLLSLTo: float | Decimal
    RTOLHSLFrom: float | Decimal
    RTOLHSLTo: float | Decimal
    RTDLLFrom: float | Decimal
    RTDLLTo: float | Decimal


NP6_323_CD_RT_PRICE_ADDER_SCED: Endpoint[
    Np6323CdRtPriceAdderSced, Np6323CdRtPriceAdderScedFilters
] = Endpoint(
    "/np6-323-cd/rt_price_adder_sced",
    Np6323CdRtPriceAdderSced,
    "np6-323-cd--rt_price_adder_sced.json",
)


class Np6324CdRt15minPriceAddersFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    deliveryHourFrom: int
    deliveryHourTo: int
    deliveryIntervalFrom: int
    deliveryIntervalTo: int
    RTRDPAFrom: float | Decimal
    RTRDPATo: float | Decimal
    RTRDPRUFrom: float | Decimal
    RTRDPRUTo: float | Decimal
    RTRDPRDFrom: float | Decimal
    RTRDPRDTo: float | Decimal
    RTRDPRRSFrom: float | Decimal
    RTRDPRRSTo: float | Decimal
    RTRDPECRSFrom: float | Decimal
    RTRDPECRSTo: float | Decimal
    RTRDPNSFrom: float | Decimal
    RTRDPNSTo: float | Decimal
    repeatHourFlag: bool


NP6_324_CD_RT_15MIN_PRICE_ADDERS: Endpoint[
    Np6324CdRt15minPriceAdders, Np6324CdRt15minPriceAddersFilters
] = Endpoint(
    "/np6-324-cd/rt_15min_price_adders",
    Np6324CdRt15minPriceAdders,
    "np6-324-cd--rt_15min_price_adders.json",
)


class Np6325CdRtdPriceAddersFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    RTDTimestampFrom: datetime
    RTDTimestampTo: datetime
    repeatHourFlag: bool
    intervalIDFrom: int
    intervalIDTo: int
    intervalEndingFrom: datetime
    intervalEndingTo: datetime
    IERepeatHourFlag: bool
    systemLambdaFrom: float | Decimal
    systemLambdaTo: float | Decimal
    RTRDPAFrom: float | Decimal
    RTRDPATo: float | Decimal
    RTRDPARUSFrom: float | Decimal
    RTRDPARUSTo: float | Decimal
    RTRDPARDSFrom: float | Decimal
    RTRDPARDSTo: float | Decimal
    RTRDPARRSFrom: float | Decimal
    RTRDPARRSTo: float | Decimal
    RTRDPAECRSFrom: float | Decimal
    RTRDPAECRSTo: float | Decimal
    RTRDPANSSFrom: float | Decimal
    RTRDPANSSTo: float | Decimal
    RTRRUCFrom: float | Decimal
    RTRRUCTo: float | Decimal
    RTRRMRFrom: float | Decimal
    RTRRMRTo: float | Decimal
    RTDNCLRFrom: float | Decimal
    RTDNCLRTo: float | Decimal
    RTDERSFrom: float | Decimal
    RTDERSTo: float | Decimal
    RTDCTIEImportFrom: float | Decimal
    RTDCTIEImportTo: float | Decimal
    RTDCTIEExportFrom: float | Decimal
    RTDCTIEExportTo: float | Decimal
    RTBLTImportFrom: float | Decimal
    RTBLTImportTo: float | Decimal
    RTBLTExportFrom: float | Decimal
    RTBLTExportTo: float | Decimal
    RTOLLSLFrom: float | Decimal
    RTOLLSLTo: float | Decimal
    RTOLHSLFrom: float | Decimal
    RTOLHSLTo: float | Decimal
    RTDLLFrom: float | Decimal
    RTDLLTo: float | Decimal


NP6_325_CD_RTD_PRICE_ADDERS: Endpoint[
    Np6325CdRtdPriceAdders, Np6325CdRtdPriceAddersFilters
] = Endpoint(
    "/np6-325-cd/rtd_price_adders",
    Np6325CdRtdPriceAdders,
    "np6-325-cd--rtd_price_adders.json",
)


class Np6326CdRtPriceSogFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    deliveryHourFrom: int
    deliveryHourTo: int
    deliveryIntervalFrom: int
    deliveryIntervalTo: int
    resourceType: str
    resourceName: str
    meterName: str
    meterPriceFrom: float | Decimal
    meterPriceTo: float | Decimal
    DSTFlag: bool


NP6_326_CD_RT_PRICE_SOG: Endpoint[Np6326CdRtPriceSog, Np6326CdRtPriceSogFilters] = (
    Endpoint(
        "/np6-326-cd/rt_price_sog", Np6326CdRtPriceSog, "np6-326-cd--rt_price_sog.json"
    )
)


class Np6327CdLmpSogPriceAddersFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    resourceType: str
    resourceName: str
    stationName: str
    voltageLevelFrom: float | Decimal
    voltageLevelTo: float | Decimal
    meterName: str
    meterLMPFrom: float | Decimal
    meterLMPTo: float | Decimal
    RTRDPAFrom: float | Decimal
    RTRDPATo: float | Decimal
    finalLMPFrom: float | Decimal
    finalLMPTo: float | Decimal
    SCEDTimestampFrom: datetime
    SCEDTimestampTo: datetime
    repeatHourFlag: bool


NP6_327_CD_LMP_SOG_PRICE_ADDERS: Endpoint[
    Np6327CdLmpSogPriceAdders, Np6327CdLmpSogPriceAddersFilters
] = Endpoint(
    "/np6-327-cd/lmp_sog_price_adders",
    Np6327CdLmpSogPriceAdders,
    "np6-327-cd--lmp_sog_price_adders.json",
)


class Np6328CdTotAsResCapFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    capREGDNFrom: float | Decimal
    capREGDNTo: float | Decimal
    capRRSFrom: float | Decimal
    capRRSTo: float | Decimal
    capECRSFrom: float | Decimal
    capECRSTo: float | Decimal
    capNSPINFrom: float | Decimal
    capNSPINTo: float | Decimal
    capREGUPRRSFrom: float | Decimal
    capREGUPRRSTo: float | Decimal
    capREGUPRRSECRSFrom: float | Decimal
    capREGUPRRSECRSTo: float | Decimal
    capREGUPRRSECRSNSPINFrom: float | Decimal
    capREGUPRRSECRSNSPINTo: float | Decimal
    SCEDTimestampFrom: datetime
    SCEDTimestampTo: datetime
    repeatHourFlag: bool
    capREGUPFrom: float | Decimal
    capREGUPTo: float | Decimal


NP6_328_CD_TOT_AS_RES_CAP: Endpoint[Np6328CdTotAsResCap, Np6328CdTotAsResCapFilters] = (
    Endpoint(
        "/np6-328-cd/tot_as_res_cap",
        Np6328CdTotAsResCap,
        "np6-328-cd--tot_as_res_cap.json",
    )
)


class Np6329CdRtdIndMcpcFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    RRSFrom: float | Decimal
    RRSTo: float | Decimal
    ECRSFrom: float | Decimal
    ECRSTo: float | Decimal
    NSPINFrom: float | Decimal
    NSPINTo: float | Decimal
    RTDTimestampFrom: datetime
    RTDTimestampTo: datetime
    repeatHourFlag: bool
    intervalIdFrom: int
    intervalIdTo: int
    intervalEndingFrom: datetime
    intervalEndingTo: datetime
    intervalRepeatHourFlag: bool
    REGUPFrom: float | Decimal
    REGUPTo: float | Decimal
    REGDNFrom: float | Decimal
    REGDNTo: float | Decimal


NP6_329_CD_RTD_IND_MCPC: Endpoint[Np6329CdRtdIndMcpc, Np6329CdRtdIndMcpcFilters] = (
    Endpoint(
        "/np6-329-cd/rtd_ind_mcpc", Np6329CdRtdIndMcpc, "np6-329-cd--rtd_ind_mcpc.json"
    )
)


class Np6331CdRtClearPriceCapFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    deliveryDateFrom: date
    deliveryDateTo: date
    deliveryHourFrom: int
    deliveryHourTo: int
    deliveryIntFrom: int
    deliveryIntTo: int
    repeatHourFlag: bool
    ASType: str
    MCPCFrom: float | Decimal
    MCPCTo: float | Decimal


NP6_331_CD_RT_CLEAR_PRICE_CAP: Endpoint[
    Np6331CdRtClearPriceCap, Np6331CdRtClearPriceCapFilters
] = Endpoint(
    "/np6-331-cd/rt_clear_price_cap",
    Np6331CdRtClearPriceCap,
    "np6-331-cd--rt_clear_price_cap.json",
)


class Np6332CdRtClearPriceCapScedFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    SCEDTimestampFrom: datetime
    SCEDTimestampTo: datetime
    repeatedHourFlag: bool
    ASType: str
    cappedMCPCFrom: float | Decimal
    cappedMCPCTo: float | Decimal
    uncappedMCPCFrom: float | Decimal
    uncappedMCPCTo: float | Decimal


NP6_332_CD_RT_CLEAR_PRICE_CAP_SCED: Endpoint[
    Np6332CdRtClearPriceCapSced, Np6332CdRtClearPriceCapScedFilters
] = Endpoint(
    "/np6-332-cd/rt_clear_price_cap_sced",
    Np6332CdRtClearPriceCapSced,
    "np6-332-cd--rt_clear_price_cap_sced.json",
)


class Np6346CdActSysLoadByFznFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    operatingDayFrom: date
    operatingDayTo: date
    hourEnding: str
    northFrom: float | Decimal
    northTo: float | Decimal
    southFrom: float | Decimal
    southTo: float | Decimal
    westFrom: float | Decimal
    westTo: float | Decimal
    houstonFrom: float | Decimal
    houstonTo: float | Decimal
    totalFrom: float | Decimal
    totalTo: float | Decimal
    DSTFlag: bool


NP6_346_CD_ACT_SYS_LOAD_BY_FZN: Endpoint[
    Np6346CdActSysLoadByFzn, Np6346CdActSysLoadByFznFilters
] = Endpoint(
    "/np6-346-cd/act_sys_load_by_fzn",
    Np6346CdActSysLoadByFzn,
    "np6-346-cd--act_sys_load_by_fzn.json",
)


class Np6787CdLmpElectricalBusFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    SCEDTimestampFrom: datetime
    SCEDTimestampTo: datetime
    repeatedHourFlag: bool
    electricalBus: str
    cappedLMPFrom: float | Decimal
    cappedLMPTo: float | Decimal
    uncappedLMPFrom: float | Decimal
    uncappedLMPTo: float | Decimal


NP6_787_CD_LMP_ELECTRICAL_BUS: Endpoint[
    Np6787CdLmpElectricalBus, Np6787CdLmpElectricalBusFilters
] = Endpoint(
    "/np6-787-cd/lmp_electrical_bus",
    Np6787CdLmpElectricalBus,
    "np6-787-cd--lmp_electrical_bus.json",
)


class Np6788CdLmpNodeZoneHubFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    SCEDTimestampFrom: datetime
    SCEDTimestampTo: datetime
    repeatHourFlag: bool
    settlementPoint: str
    LMPFrom: float | Decimal
    LMPTo: float | Decimal


NP6_788_CD_LMP_NODE_ZONE_HUB: Endpoint[
    Np6788CdLmpNodeZoneHub, Np6788CdLmpNodeZoneHubFilters
] = Endpoint(
    "/np6-788-cd/lmp_node_zone_hub",
    Np6788CdLmpNodeZoneHub,
    "np6-788-cd--lmp_node_zone_hub.json",
)


class Np686CdShdwPricesBndTrnsConstFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    fromStation: str
    toStation: str
    fromStationkVFrom: float | Decimal
    fromStationkVTo: float | Decimal
    toStationkVFrom: float | Decimal
    toStationkVTo: float | Decimal
    CCTStatus: str
    SCEDTimestampFrom: datetime
    SCEDTimestampTo: datetime
    repeatedHourFlag: bool
    constraintIDFrom: int
    constraintIDTo: int
    constraintName: str
    contingencyName: str
    shadowPriceFrom: float | Decimal
    shadowPriceTo: float | Decimal
    maxShadowPriceFrom: float | Decimal
    maxShadowPriceTo: float | Decimal
    limitFrom: float | Decimal
    limitTo: float | Decimal
    valueFrom: float | Decimal
    valueTo: float | Decimal
    violatedMWFrom: float | Decimal
    violatedMWTo: float | Decimal


NP6_86_CD_SHDW_PRICES_BND_TRNS_CONST: Endpoint[
    Np686CdShdwPricesBndTrnsConst, Np686CdShdwPricesBndTrnsConstFilters
] = Endpoint(
    "/np6-86-cd/shdw_prices_bnd_trns_const",
    Np686CdShdwPricesBndTrnsConst,
    "np6-86-cd--shdw_prices_bnd_trns_const.json",
)


class Np6915CdSumHdlLdlFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    SCEDTimestampFrom: datetime
    SCEDTimestampTo: datetime
    repeatHourFlag: bool
    GTBDFrom: float | Decimal
    GTBDTo: float | Decimal
    sumHDLFrom: float | Decimal
    sumHDLTo: float | Decimal
    sumLDLFrom: float | Decimal
    sumLDLTo: float | Decimal


NP6_915_CD_SUM_HDL_LDL: Endpoint[Np6915CdSumHdlLdl, Np6915CdSumHdlLdlFilters] = (
    Endpoint(
        "/np6-915-cd/sum_hdl_ldl", Np6915CdSumHdlLdl, "np6-915-cd--sum_hdl_ldl.json"
    )
)


class Np6970CdRtdLmpNodeZoneHubFilters(TypedDict, total=False):
    """Optional filters from the pinned current query specification."""

    RTDTimestampFrom: datetime
    RTDTimestampTo: datetime
    repeatHourFlag: bool
    intervalIdFrom: int
    intervalIdTo: int
    intervalEndingFrom: datetime
    intervalEndingTo: datetime
    intervalRepeatHourFlag: bool
    settlementPoint: str
    settlementPointType: str
    LMPFrom: float | Decimal
    LMPTo: float | Decimal


NP6_970_CD_RTD_LMP_NODE_ZONE_HUB: Endpoint[
    Np6970CdRtdLmpNodeZoneHub, Np6970CdRtdLmpNodeZoneHubFilters
] = Endpoint(
    "/np6-970-cd/rtd_lmp_node_zone_hub",
    Np6970CdRtdLmpNodeZoneHub,
    "np6-970-cd--rtd_lmp_node_zone_hub.json",
)


ENDPOINTS = (
    DAM_PRICES,
    DAM_CAPACITY_PRICES,
    RT_PRICES,
    SYSTEM_LOAD,
    GEN_55_CD_HRLY_RT_LOAD_FCAST_ACTUAL,
    NP1_302_AS_OBLIGATION,
    NP3_161_CD_7D_PLUS_AVAIL_RES_POC_MARGIN,
    NP3_162_CD_7D_AVAIL_RES_POC_MARGIN,
    NP3_233_CD_HOURLY_RES_OUTAGE_CAP,
    NP3_560_CD_7D_LOAD_FCAST_BY_FZN,
    NP3_561_CD_7D_LOAD_FCAST_BY_WZN,
    NP3_562_CD_IH_LOAD_FCAST_BY_WZN,
    NP3_565_CD_LF_BY_MODEL_WEATHER_ZONE,
    NP4_158_SG_DAM_ESSPS,
    NP4_159_CD_LOAD_DISTRIBUTION_FACTORS,
    NP4_183_CD_DAM_HOURLY_LMP,
    NP4_19_CD_DAM_AGG_AS_OFFER_CURVE,
    NP4_191_CD_DAM_SHADOW_PRICES,
    NP4_192_CD_DAM_TOTAL_ENERGY_PURCHASED,
    NP4_193_CD_TOTAL_DAM_ENERGY_SOLD,
    NP4_194_CD_DAM_PTP_OBLIGATION_SP_RESULTS,
    NP4_196_M_DAM_PRICE_CORRECTIONS_EBLMP,
    NP4_196_M_DAM_PRICE_CORRECTIONS_MCPC,
    NP4_196_M_DAM_PRICE_CORRECTIONS_SPP,
    NP4_197_M_RTM_PRICE_CORRECTIONS_EBLMP,
    NP4_197_M_RTM_PRICE_CORRECTIONS_MCPC_SCED,
    NP4_197_M_RTM_PRICE_CORRECTIONS_MCPC_SPP,
    NP4_197_M_RTM_PRICE_CORRECTIONS_SHADOW,
    NP4_197_M_RTM_PRICE_CORRECTIONS_SOGLMP,
    NP4_197_M_RTM_PRICE_CORRECTIONS_SOGPRICE,
    NP4_197_M_RTM_PRICE_CORRECTIONS_SPLMP,
    NP4_197_M_RTM_PRICE_CORRECTIONS_SPP,
    NP4_200_CD_DAM_DE_ENERGIZED_SPBC,
    NP4_212_CD_DAM_SCED_AS_DEMAND_CURVES,
    NP4_213_CD_HRUC_AS_DEMAND_CURVES,
    NP4_214_CD_DRUC_AS_DEMAND_CURVES,
    NP4_215_CD_WRUC_AS_DEMAND_CURVES,
    NP4_231_CD_ELECTRICAL_BUS_MAP_HEUR_PRICE,
    NP4_33_CD_DAM_AS_PLAN,
    NP4_523_CD_DAM_SYSTEM_LAMBDA,
    NP6_322_CD_SCED_SYSTEM_LAMBDA,
    NP6_323_CD_RT_PRICE_ADDER_SCED,
    NP6_324_CD_RT_15MIN_PRICE_ADDERS,
    NP6_325_CD_RTD_PRICE_ADDERS,
    NP6_326_CD_RT_PRICE_SOG,
    NP6_327_CD_LMP_SOG_PRICE_ADDERS,
    NP6_328_CD_TOT_AS_RES_CAP,
    NP6_329_CD_RTD_IND_MCPC,
    NP6_331_CD_RT_CLEAR_PRICE_CAP,
    NP6_332_CD_RT_CLEAR_PRICE_CAP_SCED,
    NP6_346_CD_ACT_SYS_LOAD_BY_FZN,
    NP6_787_CD_LMP_ELECTRICAL_BUS,
    NP6_788_CD_LMP_NODE_ZONE_HUB,
    NP6_86_CD_SHDW_PRICES_BND_TRNS_CONST,
    NP6_915_CD_SUM_HDL_LDL,
    NP6_970_CD_RTD_LMP_NODE_ZONE_HUB,
)
