"""Generate typed product methods from saved ERCOT operations and field metadata."""

import argparse
import json
import keyword
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUTS = ROOT / "tools" / "inputs"
TYPES = {"string": "str", "integer": "int", "number": "Decimal", "boolean": "bool"}
FORMATS = {"yyyy-MM-dd": "date", "yyyy-MM-ddTH24:mm:ss": "datetime"}
FIELDS = {
    "VARCHAR": "str",
    "INTEGER": "int",
    "LONG": "int",
    "DOUBLE": "Decimal",
    "FLOAT": "Decimal",
    "DECIMAL": "Decimal",
    "BOOLEAN": "bool",
    "DATE": "date",
    "DATETIME": "datetime",
    "TIME": "time",
}


def name(value: str) -> str:
    value = value.replace("-", "_")
    return "_" + value if value[0].isdigit() or keyword.iskeyword(value) else value


def generate(*, allow_incomplete: bool = False) -> None:
    operations = json.loads((INPUTS / "operations.json").read_text())
    schemas = json.loads((ROOT / "api_response_fields.json").read_text())
    overrides = json.loads((INPUTS / "type-overrides.json").read_text())
    row_fields = json.loads((INPUTS / "row-fields.json").read_text())
    defaults = json.loads((INPUTS / "query-defaults.json").read_text())
    groups = {}
    missing = []
    for op in operations:
        path = op["urlTemplate"].lstrip("/")
        if op["method"] != "GET" or "{" in path or "/" not in path:
            continue
        if not schemas.get(path):
            missing.append(path)
            continue
        if path in row_fields:
            schemas[path] = {name: schemas[path][name] for name in row_fields[path]}
        product, method = path.split("/")
        groups.setdefault(product, []).append((method, op, schemas[path]))
    if missing and not allow_incomplete:
        raise ValueError("Missing response schemas for: " + ", ".join(missing))
    if missing:
        print(f"Development build: {len(missing)} endpoints still need schemas")
    lines = [
        "# Generated by tools/generate_client.py; do not edit.",
        "from __future__ import annotations",
        "from collections.abc import AsyncIterator, Iterator",
        "from datetime import date, datetime, time",
        "from decimal import Decimal",
        "from typing import ClassVar",
        "from ._client import Transport, Page, Row",
        "",
    ]
    lines.append(f"__all__ = {['Client', *[name(p) for p in sorted(groups)]]!r}")
    for product, endpoints in sorted(groups.items()):
        cls = name(product)
        lines += [
            f"class {cls}:",
            "    def __init__(self, client: Transport) -> None:",
            "        self._client = client",
            "",
        ]
        for method, op, fields in endpoints:
            method = name(method)
            row = name(
                "".join(s.capitalize() for s in method.strip("_").split("_")) + "Row"
            )
            lines += [f"    class {row}(Row):"]
            path = op["urlTemplate"].lstrip("/")
            if path in row_fields:
                lines.append(
                    f"        __source_fields__: ClassVar[tuple[str, ...]] = {tuple(row_fields[path])!r}"
                )
            for field, kind in fields.items():
                if not field.isidentifier() or keyword.iskeyword(field):
                    raise ValueError(f"Unsupported field name: {product}/{field}")
                # Nullable responses are represented explicitly; absent required fields still fail.
                field_type = (
                    overrides.get(op["urlTemplate"].lstrip("/"), {})
                    .get(field, {})
                    .get("type", FIELDS[kind])
                )
                lines += [f"        {field}: {field_type} | None"]
            params = (op.get("request") or {}).get("queryParameters", [])
            for mode, prefix, result, helper in [
                ("", "def", f"Page[{cls}.{row}]", "_page"),
                ("_iter", "def", f"Iterator[{cls}.{row}]", "_iter"),
                ("_async", "async def", f"Page[{cls}.{row}]", "_apage"),
                ("_iter_async", "def", f"AsyncIterator[{cls}.{row}]", "_aiter"),
            ]:
                selected = [
                    p for p in params if not ("iter" in mode and p["name"] == "page")
                ]
                signature = ", ".join(
                    f"{name(p['name'])}: {FORMATS.get(p.get('format')) or TYPES[p['type']]} | None = {defaults.get(path, {}).get(p['name'])!r}"
                    for p in selected
                )
                signature = ", *, " + signature if signature else ""
                arguments = (
                    "{"
                    + ", ".join(f"{p['name']!r}: {name(p['name'])}" for p in selected)
                    + "}"
                )
                lines += [
                    "",
                    f"    {prefix} {method}{mode}(self{signature}) -> {result}:",
                    f"        {op['name']!r}",
                    f"        return {'await ' if mode == '_async' else ''}self._client.{helper}({op['urlTemplate']!r}, {cls}.{row}, {arguments})",
                ]
        lines.append("")
    lines += [
        "class Client(Transport):",
        '    """ERCOT public data, with generated typed product methods."""',
    ]
    for product in sorted(groups):
        cls = name(product)
        lines += [
            "",
            "    @property",
            f"    def {cls}(self) -> {cls}:",
            f"        return {cls}(self)",
        ]
    (ROOT / "tinyercot" / "_generated.py").write_text("\n".join(lines) + "\n")
    print(
        f"Generated {sum(map(len, groups.values()))} endpoints in {len(groups)} products"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--allow-incomplete",
        action="store_true",
        help="Generate available contracts during discovery; never a completeness claim",
    )
    generate(allow_incomplete=parser.parse_args().allow_incomplete)
