"""Generate current row models only from pinned observed field metadata."""

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "tools/inputs/current/dam-prices.json"
CAPACITY_INPUT = ROOT / "tools/inputs/current/dam-capacity.json"
MANIFEST = ROOT / "tools/inputs/current/provenance.json"
OUTPUT = ROOT / "tinyercot/public/_generated.py"
TYPES = {
    "DATE": "date",
    "VARCHAR": "StrictStr",
    "DOUBLE": "Decimal",
    "BOOLEAN": "StrictBool",
}
DESCRIPTIONS = {
    "deliveryDate": "Source operating date, without an inferred timezone.",
    "hourEnding": "Source hour-ending label, including 24:00.",
    "settlementPoint": "Source hub, zone, or resource-node identifier.",
    "settlementPointPrice": "Decimal source price in dollars per MWh.",
    "ancillaryType": "Source ancillary-service identifier.",
    "MCPC": "Decimal source capacity clearing price.",
    "DSTFlag": "Raw source flag; no repeated-hour meaning is inferred.",
}


def render() -> str:
    """Render the two observed non-null DAM row contracts.

    Returns:
        Model source for two verified endpoints and their ordered fields.

    Raises:
        ValueError: A pin, field type, or supported endpoint differs.
    """
    lines = [
        "# Generated by tools/generate_public.py from pinned public field metadata.",
        '"""Observed non-null DAM rows; unknown schemas fail decoding."""',
        "",
        "from datetime import date",
        "from decimal import Decimal",
        "",
        "from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr",
        "",
    ]
    for path, expected_path, model, constant in (
        (INPUT, "/np4-190-cd/dam_stlmnt_pnt_prices", "DamPrice", "DAM_FIELDS"),
        (
            CAPACITY_INPUT,
            "/np4-188-cd/dam_clear_price_for_cap",
            "DamCapacityPrice",
            "CAPACITY_FIELDS",
        ),
    ):
        raw = path.read_bytes()
        expected = json.loads(MANIFEST.read_text())["inputs"][path.name]
        if hashlib.sha256(raw).hexdigest() != expected:
            raise ValueError("Unverified current response metadata")
        contract = json.loads(raw)
        if contract["path"] != expected_path:
            raise ValueError("No row generator policy for this endpoint")
        fields = contract["fields"]
        if not fields or len({f["name"] for f in fields}) != len(fields):
            raise ValueError("Missing or duplicate response fields")
        if any(
            f["name"] not in DESCRIPTIONS or f["dataType"] not in TYPES for f in fields
        ):
            raise ValueError("Unsupported response field")
        lines.extend(
            [
                "",
                f"class {model}(BaseModel):",
                '    """A non-null row from the observed public DAM field contract.',
                "",
                "    Attributes:",
            ]
        )
        lines.extend(f"        {f['name']}: {DESCRIPTIONS[f['name']]}" for f in fields)
        lines.extend(
            [
                '    """',
                "",
                '    model_config = ConfigDict(extra="forbid", frozen=True)',
                "",
            ]
        )
        lines.extend(f"    {f['name']}: {TYPES[f['dataType']]}" for f in fields)
        lines.extend(["", "", f"{constant} = {{"])
        lines.extend(
            f"    {json.dumps(f['name'])}: {json.dumps(f['dataType'])}," for f in fields
        )
        lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> None:
    """Write or check additive models without changing legacy generation."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = render()
    if args.check:
        if OUTPUT.read_text() != output:
            raise SystemExit("Current generated models differ from the pinned inputs")
        print("Current models match pinned response metadata")
    else:
        OUTPUT.write_text(output)


if __name__ == "__main__":
    main()
